// Code generated by elval-gen. DO NOT EDIT.
// Source: generic_validation.go

package generics

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *UserRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	schema.Description = "Request with validated generic fields"
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		schema.Required = append(schema.Required, "id")

		prop.Description = "User ID (required string in Option)"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](0)

		prop.Maximum = oa.Ptr[float64](120)

		prop.Description = "Age (optional int in Option)"

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		prop.Description = "Tags (slice of strings)"

		schema.Properties["tags"] = prop
	}

	return schema
}

func (v *UserRequest) GlobalRef() string {
	return "github.com/arkannsk/elval/test/models/05_generics.UserRequest"
}
