// Code generated by elval-gen. DO NOT EDIT.
// Source: generic_validation.go

package generics

import (
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	UserRequest_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](0))
		v.AddRule(validator.Max[int](120))
		original := v
		v = validator.New[int]("Age")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *UserRequest) Validate() error {
	var err *errs.ValidationError
	{
		wrapper := elval.UnwrapGeneric[string](v.ID)
		if !wrapper.IsPresent() {
			return errs.NewValidationError("ID", "required", "not present")
		}
	}
	{
		wrapper := elval.UnwrapGeneric[int](v.Age)
		if wrapper.IsPresent() {
			val, _ := wrapper.Value()
			if err = UserRequest_AgeValidator.Validate(val); err != nil {
				return err
			}
		}
	}
	return err
}
