// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package product

import (
	"fmt"
	"github.com/arkannsk/elval/pkg/validator"
)

// Validate проверяет структуру Product
func (v *Product) Validate() error {
	var errs []error
	// Валидация поля Status

	{

		builder := validator.New[string]("Status")
		builder.AddRule(validator.Required[string]())
		builder.AddRule(validator.Eq("active"))
		if err := builder.Validate(v.Status); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Quantity

	{

		builder := validator.New[int]("Quantity")
		builder.AddRule(validator.Required[int]())
		builder.AddRule(validator.Min[int](1))
		builder.AddRule(validator.Max[int](100))
		if err := builder.Validate(v.Quantity); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Price

	{

		builder := validator.New[float64]("Price")
		builder.AddRule(validator.Required[float64]())
		builder.AddRule(validator.Gt[float64](0))
		if err := builder.Validate(v.Price); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Age

	{

		builder := validator.New[int]("Age")
		builder.AddRule(validator.Required[int]())
		builder.AddRule(validator.Gte[int](18))
		if err := builder.Validate(v.Age); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Role

	{

		builder := validator.New[string]("Role")
		builder.AddRule(validator.Eq("admin"))
		if v.Role != "" {
			if err := builder.Validate(v.Role); err != nil {
				errs = append(errs, err)
			}
		}
	}

	// Валидация поля Score

	{

		builder := validator.New[int]("Score")
		builder.AddRule(validator.Neq[int](0))
		if err := builder.Validate(v.Score); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Discount

	{

		builder := validator.New[int]("Discount")
		builder.AddRule(validator.Lt[int](100))
		if err := builder.Validate(v.Discount); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Tax

	{

		builder := validator.New[int]("Tax")
		builder.AddRule(validator.Lte[int](50))
		if err := builder.Validate(v.Tax); err != nil {
			errs = append(errs, err)
		}
	}

	if len(errs) > 0 {
		return fmt.Errorf("ошибки валидации: %v", errs)
	}
	return nil

}
