// pkg/generator/templates/header.tmpl

// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package product

import (
	"context"
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	Product_StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Eq[string]("active"))
		return v
	}()

	Product_QuantityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Quantity")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](100))
		return v
	}()

	Product_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Required[float64]())
		v.AddRule(validator.Gt[float64](0))
		return v
	}()

	Product_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Gte[int](18))
		return v
	}()

	Product_RoleValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Role")
		v.AddRule(validator.Eq[string]("admin"))
		original := v
		v = validator.New[string]("Role")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Product_ScoreValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Score")
		v.AddRule(validator.Neq[int](0))
		return v
	}()

	Product_DiscountValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Discount")
		v.AddRule(validator.Lt[int](100))
		return v
	}()

	Product_TaxValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Tax")
		v.AddRule(validator.Lte[int](50))
		return v
	}()
)

// Decorate применяет декораторы к структуре Product
func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

// Validate проверяет структуру Product
func (v *Product) Validate() error {

	if err := Product_StatusValidator.Validate(v.Status); err != nil {
		return err
	}

	if err := Product_QuantityValidator.Validate(v.Quantity); err != nil {
		return err
	}

	if err := Product_PriceValidator.Validate(v.Price); err != nil {
		return err
	}

	if err := Product_AgeValidator.Validate(v.Age); err != nil {
		return err
	}

	if err := Product_RoleValidator.Validate(v.Role); err != nil {
		return err
	}

	if err := Product_ScoreValidator.Validate(v.Score); err != nil {
		return err
	}

	if err := Product_DiscountValidator.Validate(v.Discount); err != nil {
		return err
	}

	if err := Product_TaxValidator.Validate(v.Tax); err != nil {
		return err
	}
	return nil
}
