// Code generated by elval-gen. DO NOT EDIT.
// Source: directive_errors.go

package invalid_directives

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	MixedValidationErrors_BioValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Bio")
		v.AddRule(validator.MinLen(3))
		original := v
		v = validator.New[string]("Bio")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *MixedValidationErrors) Validate() error {
	var err *errs.ValidationError
	if v.Name == "" {
		return errs.NewValidationError("Name", "required", "field is required")
	}
	if v.Bio != nil {
		val := *v.Bio
		if err = MixedValidationErrors_BioValidator.Validate(val); err != nil {
			return err
		}
	}
	return err
}
