// Code generated by elval-gen. DO NOT EDIT.
// Source: directive_errors.go

package invalid_directives

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	MixedValidationErrors_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		return v
	}()

	MixedValidationErrors_BioValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Bio")
		v.AddRule(validator.MinLen(3))
		original := v
		v = validator.New[string]("Bio")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *MixedValidationErrors) Decorate(ctx context.Context) error {

	return nil
}

func (v *MixedValidationErrors) Validate() error {
	var err *errs.ValidationError
	if err = MixedValidationErrors_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	// Указатель Bio
	if v.Bio != nil {
		val := *v.Bio
		if err := MixedValidationErrors_BioValidator.Validate(val); err != nil {
			return &errs.ValidationError{
				Field:   "Bio",
				Rule:    "nested",
				Message: "поле Bio: " + err.Error(),
			}
		}
	}

	return nil
}
