// Code generated by elval-gen. DO NOT EDIT.
// Source: directive_errors.go

package invalid_directives

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *MixedValidationErrors) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 8),
		Required:   make([]string, 0, 8),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["phone"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["score"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["age"] = prop
	}

	{
		prop := &oa.Schema{}

		schema.Properties["timeout"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["range"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["status"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Minimum = oa.Ptr[float64](3)

		schema.Properties["bio"] = prop
	}

	return schema
}

func (v *MixedValidationErrors) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/invalid_directives.MixedValidationErrors"
}
