// Code generated by elval-gen. DO NOT EDIT.
// Source: geo.go

package docs

import (
	oa "github.com/arkannsk/elval/pkg/oa"
)

func (v *PointDocs) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Properties["type"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "number"

		prop.Title = "Coordinates"
		prop.Description = "[longitude, latitude]"
		prop.Example = `[37.6173, 55.7558]`

		schema.Properties["coordinates"] = prop
	}

	return schema
}

func (v *PointDocs) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/geo_polymorphism/docs.PointDocs"
}

func (v *PolygonDocs) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Properties["type"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Type = "array"
		prop.Items.Items = &oa.Schema{}

		prop.Items.Items.Type = "number"

		prop.Title = "Coordinates"
		prop.Description = "Array of linear rings"

		schema.Properties["coordinates"] = prop
	}

	return schema
}

func (v *PolygonDocs) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/geo_polymorphism/docs.PolygonDocs"
}

func (v *FeatureDocs) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Title = "Geometry"
		prop.Description = "The geometric shape"
		prop.OneOf = []oa.Schema{
			{Ref: "#/components/schemas/github.com/arkannsk/elval/test/integration/geo_polymorphism/docs.PointDocs"},
			{Ref: "#/components/schemas/github.com/arkannsk/elval/test/integration/geo_polymorphism/docs.PolygonDocs"},
		}

		schema.Properties["geometry"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Title = "Properties"
		prop.Description = "Arbitrary properties"

		schema.Properties["properties"] = prop
	}

	schema.Discriminator = &oa.Discriminator{
		PropertyName: "geometry.type",
		Mapping: map[string]string{
			"Point":   "PointFeature",
			"Polygon": "PolygonFeature",
		},
	}

	return schema
}

func (v *FeatureDocs) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/geo_polymorphism/docs.FeatureDocs"
}
