// Code generated by elval-gen. DO NOT EDIT.
// Source: date_validation.go

package date_validation

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	Event_CreatedAtValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("CreatedAt")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("RFC3339"))
		return v
	}()

	Event_UpdatedAtValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("UpdatedAt")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("RFC3339", "RFC3339Nano"))
		return v
	}()

	Event_DateOnlyValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("DateOnly")
		v.AddRule(validator.Date("2006-01-02"))
		original := v
		v = validator.New[string]("DateOnly")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Event_TimestampValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Timestamp")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("2006-01-02T15:04:05", "RFC3339"))
		return v
	}()
)

var (
	LogEntry_EventTimeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("EventTime")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("2006-01-02T15:04:05Z07:00", "RFC3339"))
		return v
	}()
)

func (v *Event) Validate() error {
	var err *errs.ValidationError
	if v.CreatedAt == "" {
		return errs.NewValidationError("CreatedAt", "required", "field is required")
	}
	if err = Event_CreatedAtValidator.Validate(v.CreatedAt); err != nil {
		return err
	}
	if v.UpdatedAt == "" {
		return errs.NewValidationError("UpdatedAt", "required", "field is required")
	}
	if err = Event_UpdatedAtValidator.Validate(v.UpdatedAt); err != nil {
		return err
	}
	if err = Event_DateOnlyValidator.Validate(v.DateOnly); err != nil {
		return err
	}
	if v.Timestamp == "" {
		return errs.NewValidationError("Timestamp", "required", "field is required")
	}
	if err = Event_TimestampValidator.Validate(v.Timestamp); err != nil {
		return err
	}
	return err
}

func (v *LogEntry) Validate() error {
	var err *errs.ValidationError
	if v.EventTime == "" {
		return errs.NewValidationError("EventTime", "required", "field is required")
	}
	if err = LogEntry_EventTimeValidator.Validate(v.EventTime); err != nil {
		return err
	}
	return err
}
