// Code generated by elval-gen. DO NOT EDIT.
// Source: date_validation.go

package date_validation

import (
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	Event_CreatedAtValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("CreatedAt")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("RFC3339"))
		return v
	}()

	Event_UpdatedAtValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("UpdatedAt")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("RFC3339", "RFC3339Nano"))
		return v
	}()

	Event_DateOnlyValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("DateOnly")
		v.AddRule(validator.Date("2006-01-02"))
		original := v
		v = validator.New[string]("DateOnly")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Event_TimestampValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Timestamp")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("2006-01-02T15:04:05", "RFC3339"))
		return v
	}()
)

func (v *Event) Validate() error {

	if err := Event_CreatedAtValidator.Validate(v.CreatedAt); err != nil {
		return err
	}

	if err := Event_UpdatedAtValidator.Validate(v.UpdatedAt); err != nil {
		return err
	}

	if err := Event_DateOnlyValidator.Validate(v.DateOnly); err != nil {
		return err
	}

	if err := Event_TimestampValidator.Validate(v.Timestamp); err != nil {
		return err
	}
	return nil
}

var (
	LogEntry_EventTimeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("EventTime")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Date("2006-01-02T15:04:05Z07:00", "RFC3339"))
		return v
	}()

	LogEntry_KitchenTimeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("KitchenTime")
		v.AddRule(validator.Date("Kitchen"))
		original := v
		v = validator.New[string]("KitchenTime")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *LogEntry) Validate() error {

	if err := LogEntry_EventTimeValidator.Validate(v.EventTime); err != nil {
		return err
	}

	if err := LogEntry_KitchenTimeValidator.Validate(v.KitchenTime); err != nil {
		return err
	}
	return nil
}
