// Code generated by elval-gen. DO NOT EDIT.
// Source: date_validation.go

package date_validation

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Event) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "createdat")

		schema.Properties["createdat"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "updatedat")

		schema.Properties["updatedat"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["dateonly"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "timestamp")

		schema.Properties["timestamp"] = prop
	}

	return schema
}

func (v *Event) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/date_validation.Event"
}

func (v *LogEntry) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "eventtime")

		schema.Properties["eventtime"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["kitchentime"] = prop
	}

	return schema
}

func (v *LogEntry) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/date_validation.LogEntry"
}
