// Code generated by elval-gen. DO NOT EDIT.
// Source: api.go

package geo_polymorphism

import (
	oa "github.com/arkannsk/elval/pkg/oa"
)

func (v *CreateLocationRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}
		prop.Ref = "#/components/schemas/github.com/arkannsk/elval/test/integration/geo_polymorphism/docs.FeatureDocs"

		schema.Properties["feature"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Properties["userid"] = prop
	}

	return schema
}

func (v *CreateLocationRequest) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/geo_polymorphism.CreateLocationRequest"
}

func (v *ListLocationsResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Ref = "#/components/schemas/github.com/arkannsk/elval/test/integration/geo_polymorphism/docs.FeatureDocs"

		schema.Properties["features"] = prop
	}

	return schema
}

func (v *ListLocationsResponse) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/geo_polymorphism.ListLocationsResponse"
}
