// Code generated by elval-gen. DO NOT EDIT.
// Source: enum.go

package enum

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Order) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "status")
		prop.Enum = []any{"pending", "processing", "shipped", "delivered", "cancelled"}

		schema.Properties["status"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Required = append(schema.Required, "priority")
		prop.Enum = []any{"1", "2", "3", "4", "5"}

		schema.Properties["priority"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Enum = []any{"small", "medium", "large"}

		schema.Properties["size"] = prop
	}

	return schema
}

func (v *Order) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/enum.Order"
}

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "role")
		prop.Enum = []any{"admin", "moderator", "user"}

		schema.Properties["role"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Required = append(schema.Required, "level")
		prop.Enum = []any{"1", "2", "3"}

		schema.Properties["level"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/enum.User"
}
