// Code generated by elval-gen. DO NOT EDIT.
// Source: enum.go

package enum

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	Order_StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Enum[string]("pending", "processing", "shipped", "delivered", "cancelled"))
		return v
	}()

	Order_PriorityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Priority")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Enum[int](1, 2, 3, 4, 5))
		return v
	}()

	Order_SizeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Size")
		v.AddRule(validator.Enum[string]("small", "medium", "large"))
		original := v
		v = validator.New[string]("Size")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *Order) Decorate(ctx context.Context) error {

	return nil
}

func (v *Order) Validate() error {
	var err *errs.ValidationError
	if err = Order_StatusValidator.Validate(v.Status); err != nil {
		return err
	}
	if err = Order_PriorityValidator.Validate(v.Priority); err != nil {
		return err
	}
	if err = Order_SizeValidator.Validate(v.Size); err != nil {
		return err
	}
	return nil
}

var (
	User_RoleValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Role")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Enum[string]("admin", "moderator", "user"))
		return v
	}()

	User_LevelValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Level")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Enum[int](1, 2, 3))
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	return nil
}

func (v *User) Validate() error {
	var err *errs.ValidationError
	if err = User_RoleValidator.Validate(v.Role); err != nil {
		return err
	}
	if err = User_LevelValidator.Validate(v.Level); err != nil {
		return err
	}
	return nil
}
