// pkg/generator/templates/validator.tmpl

// Code generated by elval-gen. DO NOT EDIT.
// Source: person.go

package person

import (
	"fmt"
	"github.com/arkannsk/elval/pkg/validator"
	"time"
)

// Validate проверяет структуру Person
func (v *Person) Validate() error {
	var errs []error
	// Валидация поля Name
	{

		rules := []validator.ValidationRule[string]{}
		rules = append(rules, validator.Required[string]())
		rules = append(rules, validator.MinLen(2))
		rules = append(rules, validator.MaxLen(100))
		if err := validator.ValidateFunc("Name", v.Name, rules...); err != nil {
			errs = append(errs, err)
		}
	}
	// Валидация поля Email
	{

		rules := []validator.ValidationRule[string]{}
		rules = append(rules, validator.Required[string]())
		rules = append(rules, validator.Email())
		if err := validator.ValidateFunc("Email", v.Email, rules...); err != nil {
			errs = append(errs, err)
		}
	}
	// Валидация поля Age
	{

		rules := []validator.ValidationRule[int]{}
		rules = append(rules, validator.Required[int]())
		rules = append(rules, validator.Min[int](18))
		rules = append(rules, validator.Max[int](120))
		if err := validator.ValidateFunc("Age", v.Age, rules...); err != nil {
			errs = append(errs, err)
		}
	}
	// Валидация поля Phone
	{

		rules := []validator.ValidationRule[string]{}
		rules = append(rules, validator.Phone())
		// Поле опционально - проверяем только если не пустое
		if v.Phone != "" {
			if err := validator.ValidateFunc("Phone", v.Phone, rules...); err != nil {
				errs = append(errs, err)
			}
		}
	}
	// Валидация поля BirthDate
	{

		rules := []validator.ValidationRule[time.Time]{}
		rules = append(rules, validator.Required[time.Time]())
		rules = append(rules, validator.After("2006-01-02", "1900-01-01"))
		rules = append(rules, validator.Before("2006-01-02", "2024-12-31"))
		if err := validator.ValidateFunc("BirthDate", v.BirthDate, rules...); err != nil {
			errs = append(errs, err)
		}
	}
	// Валидация поля Tags
	{
		sliceValidator := validator.NewSliceValidator[string]("Tags")
		sliceValidator.Required()
		sliceValidator.Min(1)
		sliceValidator.Max(10)
		if err := sliceValidator.Validate(v.Tags); err != nil {
			errs = append(errs, err)
		}
	}
	// Валидация поля Scores
	{
		sliceValidator := validator.NewSliceValidator[int]("Scores")
		sliceValidator.NotZero()
		if err := sliceValidator.Validate(v.Scores); err != nil {
			errs = append(errs, err)
		}
	}

	if len(errs) > 0 {
		return fmt.Errorf("ошибки валидации: %v", errs)
	}
	return nil
}
