// Code generated by elval-gen. DO NOT EDIT.
// Source: response.go

package response_content

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *UserResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["email"] = prop
	}

	return schema
}

func (v *UserResponse) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/response_content.UserResponse"
}
func (v *UserResponse) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[200] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
			"application/xml":  {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	return responses
}

func (v *ErrorResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["code"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["message"] = prop
	}

	return schema
}

func (v *ErrorResponse) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/response_content.ErrorResponse"
}
func (v *ErrorResponse) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[400] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	return responses
}

func (v *CreateUserResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}

	return schema
}

func (v *CreateUserResponse) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/response_content.CreateUserResponse"
}
func (v *CreateUserResponse) OaResponses() map[int]*oa.Response {
	responses := make(map[int]*oa.Response)
	responses[200] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
			"application/xml":  {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	responses[201] = &oa.Response{
		Description: v.GlobalRef(),
		Content: map[string]*oa.MediaType{
			"application/json": {Schema: &oa.Schema{Ref: "#/components/schemas/" + v.GlobalRef()}},
		},
	}
	return responses
}
