// Code generated by elval-gen. DO NOT EDIT.
// Source: main.go

package main

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 7),
		Required:   make([]string, 0, 7),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["phone"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"
		prop.Format = "date-time"

		schema.Properties["birthdate"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		schema.Properties["tags"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "integer"

		schema.Properties["scores"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/examples/struct.User"
}
