// Code generated by elval-gen. DO NOT EDIT.
// Source: address.go

package order

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Address) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Example = "Warehouse A"

		schema.Properties["warehouse"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Example = "Zone B-12"

		schema.Properties["zone"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Example = "12:00-18:00"

		schema.Properties["deliverywindow"] = prop
	}

	return schema
}

func (v *Address) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_unique_refs/order.Address"
}
