// Code generated by elval-gen. DO NOT EDIT.
// Source: order.go

package order

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Order) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Example = "order-456"

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Example = "2999.99"

		schema.Properties["total"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Example = "{\"warehouse\":\"Main\",\"zone\":\"A-1\",\"deliveryWindow\":\"09:00-12:00\"}"

		schema.Properties["shippingaddress"] = prop
	}

	return schema
}

func (v *Order) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_unique_refs/order.Order"
}
