// Code generated by elval-gen. DO NOT EDIT.
// Source: complex_request.go

package user_http_request

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	ComplexRequest_UserIDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("UserID")
		v.AddRule(validator.Required[string]())
		return v
	}()

	ComplexRequest_VersionValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Version")
		v.AddRule(validator.Required[int]())
		return v
	}()

	ComplexRequest_PageValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Page")
		v.AddRule(validator.Required[int]())
		return v
	}()

	ComplexRequest_LimitValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Limit")
		v.AddRule(validator.Min[int](1))
		return v
	}()
)

func (v *ComplexRequest) Decorate(ctx context.Context) error {

	return nil
}

func (v *ComplexRequest) Validate() error {
	var err *errs.ValidationError
	if err = ComplexRequest_UserIDValidator.Validate(v.UserID); err != nil {
		return err
	}
	if err = ComplexRequest_VersionValidator.Validate(v.Version); err != nil {
		return err
	}
	if err = ComplexRequest_PageValidator.Validate(v.Page); err != nil {
		return err
	}
	if err = ComplexRequest_LimitValidator.Validate(v.Limit); err != nil {
		return err
	}

	if true && len(v.IDs) == 0 {
		return &errs.ValidationError{
			Field:   "IDs",
			Rule:    "required",
			Message: "поле IDs обязательно",
		}
	}

	if false && len(v.Tags) == 0 {
		return &errs.ValidationError{
			Field:   "Tags",
			Rule:    "required",
			Message: "поле Tags обязательно",
		}
	}

	return nil
}
