// Code generated by elval-gen. DO NOT EDIT.
// Source: complex_request.go

package user_http_request

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	oa "github.com/arkannsk/elval/pkg/openapi"
	"net/http"
	"strconv"
	"time"
)

func (v *ComplexRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Internal role filter (not from HTTP params)"

		schema.Properties["role"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Description = "Metadata map"

		schema.Properties["metadata"] = prop
	}

	return schema
}

func (v *ComplexRequest) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/user_http_request.ComplexRequest"
}

// OaParams возвращает параметры OpenAPI для этой структуры
func (v *ComplexRequest) OaParams() []*oa.Parameter {
	params := []*oa.Parameter{}

	params = append(params, &oa.Parameter{
		Name:     "id",
		In:       oa.ParamPath,
		Required: true,
		Schema:   v.getFieldSchema("UserID"),
	})

	params = append(params, &oa.Parameter{
		Name:     "version",
		In:       oa.ParamPath,
		Required: true,
		Schema:   v.getFieldSchema("Version"),
	})

	params = append(params, &oa.Parameter{
		Name:     "page",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("Page"),
	})

	params = append(params, &oa.Parameter{
		Name:     "limit",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("Limit"),
	})

	params = append(params, &oa.Parameter{
		Name:     "ids",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("IDs"),
	})

	params = append(params, &oa.Parameter{
		Name:     "tags",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("Tags"),
	})

	params = append(params, &oa.Parameter{
		Name:     "active",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("Active"),
	})

	params = append(params, &oa.Parameter{
		Name:     "created_after",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("CreatedAfter"),
	})

	params = append(params, &oa.Parameter{
		Name:     "score",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("Score"),
	})

	params = append(params, &oa.Parameter{
		Name:     "X-Request-ID",
		In:       oa.ParamHeader,
		Required: false,
		Schema:   v.getFieldSchema("RequestID"),
	})

	params = append(params, &oa.Parameter{
		Name:     "X-Tenant-ID",
		In:       oa.ParamHeader,
		Required: false,
		Schema:   v.getFieldSchema("TenantID"),
	})

	params = append(params, &oa.Parameter{
		Name:     "X-Rate-Limit",
		In:       oa.ParamHeader,
		Required: false,
		Schema:   v.getFieldSchema("RateLimit"),
	})
	return params
}

// getFieldSchema вспомогательный метод для получения схемы конкретного поля
func (v *ComplexRequest) getFieldSchema(fieldName string) *oa.Schema {
	switch fieldName {
	case "UserID":

		return &oa.Schema{
			Type:   "string",
			Format: "uuid",
		}
	case "Version":

		return &oa.Schema{
			Type: "integer",
		}
	case "Page":

		return &oa.Schema{
			Type: "integer",
		}
	case "Limit":

		return &oa.Schema{
			Type: "integer",
		}
	case "IDs":

		return &oa.Schema{
			Type: "array",

			Items: &oa.Schema{
				Type: "integer",
			},
		}
	case "Tags":

		return &oa.Schema{
			Type: "array",

			Items: &oa.Schema{
				Type: "string",
			},
		}
	case "Active":

		return &oa.Schema{
			Type: "boolean",
		}
	case "CreatedAfter":

		return &oa.Schema{
			Type:   "string",
			Format: "date-time",
		}
	case "Score":

		return &oa.Schema{
			Type: "number",
		}
	case "RequestID":

		return &oa.Schema{
			Type: "string",
		}
	case "TenantID":

		return &oa.Schema{
			Type: "integer",
		}
	case "RateLimit":

		return &oa.Schema{
			Type: "object",
		}
	case "Role":

		return &oa.Schema{
			Type: "string",
		}
	case "Metadata":

		return &oa.Schema{
			Type: "object",
		}
	default:
		return nil
	}
}

func (v *ComplexRequest) ParseRequest(r *http.Request) error {
	{

		// Parameter: id (path)
		// Parsing primitive: string
		v.UserID = r.PathValue("id")
	}
	{

		// Parameter: version (path)
		// Parsing primitive: int
		if val := r.PathValue("version"); val != "" {
			parsedInt, err := strconv.ParseInt(val, 10, 64)
			if err != nil {
				return errs.NewParseRequestError("Version", val, "invalid integer")
			}
			v.Version = int(parsedInt)
		}
	}
	{

		// Parameter: page (query)
		// Parsing primitive: int
		if vals := r.URL.Query()["page"]; len(vals) > 0 {
			parsedInt, err := strconv.ParseInt(vals[0], 10, 64)
			if err != nil {
				return errs.NewParseRequestError("Page", vals[0], "invalid integer")
			}
			v.Page = int(parsedInt)
		}
	}
	{

		// Parameter: limit (query)
		// Parsing primitive: int
		if vals := r.URL.Query()["limit"]; len(vals) > 0 {
			parsedInt, err := strconv.ParseInt(vals[0], 10, 64)
			if err != nil {
				return errs.NewParseRequestError("Limit", vals[0], "invalid integer")
			}
			v.Limit = int(parsedInt)
		}
	}
	{

		// Parameter: ids (query)
		// Parsing slice: int[]
		var result []int
		for _, v := range r.URL.Query()["ids"] {
			val, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return errs.NewParseRequestError("IDs", v, "invalid integer in slice")
			}
			result = append(result, int(val))
		}
		v.IDs = result
	}
	{

		// Parameter: tags (query)
		// Parsing slice: string[]
		v.Tags = r.URL.Query()["tags"]
	}
	{

		// Parameter: active (query)
		// Parsing primitive: bool
		if vals := r.URL.Query()["active"]; len(vals) > 0 {
			parsedBool, err := strconv.ParseBool(vals[0])
			if err != nil {
				return errs.NewParseRequestError("Active", vals[0], "invalid bool")
			}
			v.Active = parsedBool
		}
	}
	{

		// Parameter: created_after (query)
		// Parsing primitive: time.Time
		if vals := r.URL.Query()["created_after"]; len(vals) > 0 {
			parsedTime, err := time.Parse(time.RFC3339, vals[0])
			if err != nil {
				return errs.NewParseRequestError("CreatedAfter", vals[0], "invalid time format (RFC3339)")
			}
			v.CreatedAfter = parsedTime
		}
	}
	{

		// Parameter: score (query)
		// Parsing primitive: float64
		if vals := r.URL.Query()["score"]; len(vals) > 0 {
			parsedFloat, err := strconv.ParseFloat(vals[0], 64)
			if err != nil {
				return errs.NewParseRequestError("Score", vals[0], "invalid float")
			}
			v.Score = parsedFloat
		}
	}
	{

		// Parameter: X-Request-ID (header)
		// Parsing primitive: string
		v.RequestID = r.Header.Get("X-Request-ID")
	}
	{

		// Parameter: X-Tenant-ID (header)
		// Parsing primitive: int64
		if val := r.Header.Get("X-Tenant-ID"); val != "" {
			parsedInt, err := strconv.ParseInt(val, 10, 64)
			if err != nil {
				return errs.NewParseRequestError("TenantID", val, "invalid integer")
			}
			v.TenantID = parsedInt
		}
	}
	{

		// Parameter: X-Rate-Limit (header)
		// Parsing primitive: uint32
		if val := r.Header.Get("X-Rate-Limit"); val != "" {
			parsedUint, err := strconv.ParseUint(val, 10, 64)
			if err != nil {
				return errs.NewParseRequestError("RateLimit", val, "invalid uint")
			}
			v.RateLimit = uint32(parsedUint)
		}
	}
	return nil
}
