// Code generated by elval-gen. DO NOT EDIT.
// Source: user_request.go

package user_http_request

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
	"net/http"
)

func (v *GetUserRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "Internal user role filter"

		schema.Properties["role"] = prop
	}

	return schema
}

func (v *GetUserRequest) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/user_http_request.GetUserRequest"
}

// OaParams возвращает параметры OpenAPI для этой структуры
func (v *GetUserRequest) OaParams() []*oa.Parameter {
	params := []*oa.Parameter{}

	params = append(params, &oa.Parameter{
		Name:     "id",
		In:       oa.ParamPath,
		Required: true,
		Schema:   v.getFieldSchema("ID"),
	})

	params = append(params, &oa.Parameter{
		Name:     "fields",
		In:       oa.ParamQuery,
		Required: false,
		Schema:   v.getFieldSchema("Fields"),
	})

	params = append(params, &oa.Parameter{
		Name:     "X-Request-ID",
		In:       oa.ParamHeader,
		Required: false,
		Schema:   v.getFieldSchema("RequestID"),
	})
	return params
}

// getFieldSchema вспомогательный метод для получения схемы конкретного поля
func (v *GetUserRequest) getFieldSchema(fieldName string) *oa.Schema {
	switch fieldName {
	case "ID":

		return &oa.Schema{
			Type:   "string",
			Format: "uuid",
		}
	case "Fields":

		return &oa.Schema{
			Type: "array",

			Items: &oa.Schema{
				Type: "string",
			},
		}
	case "RequestID":

		return &oa.Schema{
			Type: "string",
		}
	case "Role":

		return &oa.Schema{
			Type: "string",
		}
	default:
		return nil
	}
}

func (v *GetUserRequest) ParseRequest(r *http.Request) error {
	{

		// Parameter: id (path)
		// Parsing primitive: string
		v.ID = r.PathValue("id")
	}
	{

		// Parameter: fields (query)
		// Parsing slice: string[]
		v.Fields = r.URL.Query()["fields"]
	}
	{

		// Parameter: X-Request-ID (header)
		// Parsing primitive: string
		v.RequestID = r.Header.Get("X-Request-ID")
	}
	return nil
}
