// Code generated by elval-gen. DO NOT EDIT.
// Source: user_request.go

package user_http_request

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	GetUserRequest_IDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ID")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.UUID())
		return v
	}()
)

func (v *GetUserRequest) Decorate(ctx context.Context) error {

	return nil
}

func (v *GetUserRequest) Validate() error {
	var err *errs.ValidationError
	if err = GetUserRequest_IDValidator.Validate(v.ID); err != nil {
		return err
	}

	if false && len(v.Fields) == 0 {
		return &errs.ValidationError{
			Field:   "Fields",
			Rule:    "required",
			Message: "поле Fields обязательно",
		}
	}

	return nil
}
