// Code generated by elval-gen. DO NOT EDIT.
// Source: invalid.go

package invalid

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	InvalidUser_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		return v
	}()

	InvalidUser_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.MatchRegexp("invalid[regexp"))
		return v
	}()

	InvalidUser_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Min[float64](1.5))
		v.AddRule(validator.Max[float64](10.5))
		return v
	}()
)

func (v *InvalidUser) Decorate(ctx context.Context) error {

	return nil
}

func (v *InvalidUser) Validate() error {
	var err *errs.ValidationError
	if err = InvalidUser_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	if err = InvalidUser_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	if false && len(v.Tags) == 0 {
		return &errs.ValidationError{
			Field:   "Tags",
			Rule:    "required",
			Message: "поле Tags обязательно",
		}
	}
	if len(v.Tags) < 3 {
		return &errs.ValidationError{
			Field:   "Tags",
			Rule:    "min",
			Message: "поле Tags должно содержать минимум 3 элементов",
		}
	}
	if len(v.Tags) > 2 {
		return &errs.ValidationError{
			Field:   "Tags",
			Rule:    "max",
			Message: "поле Tags должно содержать максимум 2 элементов",
		}
	}

	if false && len(v.Items) == 0 {
		return &errs.ValidationError{
			Field:   "Items",
			Rule:    "required",
			Message: "поле Items обязательно",
		}
	}
	if len(v.Items) < 3 {
		return &errs.ValidationError{
			Field:   "Items",
			Rule:    "min",
			Message: "поле Items должно содержать минимум 3 элементов",
		}
	}
	if len(v.Items) > 2 {
		return &errs.ValidationError{
			Field:   "Items",
			Rule:    "max",
			Message: "поле Items должно содержать максимум 2 элементов",
		}
	}

	if err = InvalidUser_PriceValidator.Validate(v.Price); err != nil {
		return err
	}
	return nil
}
