// Code generated by elval-gen. DO NOT EDIT.
// Source: invalid.go

package invalid

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *InvalidUser) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 9),
		Required:   make([]string, 0, 9),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["age"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["score"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = "invalid[regexp"

		schema.Properties["email"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["role"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"
		prop.Format = "date-time"

		schema.Properties["createdat"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		prop.Minimum = oa.Ptr[float64](3)
		prop.Maximum = oa.Ptr[float64](2)

		schema.Properties["tags"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		prop.Minimum = oa.Ptr[float64](3)
		prop.Maximum = oa.Ptr[float64](2)

		schema.Properties["items"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Minimum = oa.Ptr[float64](1.5)
		prop.Maximum = oa.Ptr[float64](10.5)

		schema.Properties["price"] = prop
	}

	return schema
}

func (v *InvalidUser) GlobalRef() string {
	return "github.com/arkannsk/elval/test/lint/invalid.InvalidUser"
}
