// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package main

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	"github.com/arkannsk/elval/pkg/validator"
	mo "github.com/samber/mo"
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(func(value any) error {
			return validator.ValidateCustom("x-option-present", value, "")
		})
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(func(value any) error {
			return validator.ValidateCustom("x-option-value-min", value, "3")
		})
		v.AddRule(func(value any) error {
			return validator.ValidateCustom("x-option-value-max", value, "50")
		})
		return v
	}()

	User_PhoneValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Phone")
		v.AddRule(func(value any) error {
			return validator.ValidateCustom("x-option-absent", value, "")
		})
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	return nil
}

func (v *User) Validate() error {
	var err *errs.ValidationError
	if !v.Name.IsPresent() {
		return &errs.ValidationError{Field: "Name", Rule: "required", Message: errs.ErrRequired.Message}
	}
	if val, ok := v.Name.Value(); ok {
		if err = User_NameValidator.Validate(val); err != nil {
			return err
		}
	}
	if !v.Email.IsPresent() {
		return &errs.ValidationError{Field: "Email", Rule: "required", Message: errs.ErrRequired.Message}
	}
	if val, ok := v.Email.Value(); ok {
		if err = User_EmailValidator.Validate(val); err != nil {
			return err
		}
	}
	if val, ok := v.Phone.Value(); ok {
		if err = User_PhoneValidator.Validate(val); err != nil {
			return err
		}
	}
	return nil
}
