// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package main

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		schema.Required = append(schema.Required, "email")

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"

		schema.Properties["phone"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/examples/custom_external_type.User"
}
