// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package main

import (
	"context"
	"github.com/arkannsk/elval/pkg/validator"
)

var ()

// Decorate применяет декораторы к структуре User
func (v *User) Decorate(ctx context.Context) error {

	return nil
}

// Validate проверяет структуру User
func (v *User) Validate() error {

	// Кастомная валидация поля Name
	if err := validator.ValidateCustom("x-option-present", v.Name, ""); err != nil {
		return &validator.ValidationError{
			Field:   "Name",
			Rule:    "x-option-present",
			Message: err.Error(),
		}
	}

	// Кастомная валидация поля Email
	if err := validator.ValidateCustom("x-option-value-min", v.Email, "3"); err != nil {
		return &validator.ValidationError{
			Field:   "Email",
			Rule:    "x-option-value-min",
			Message: err.Error(),
		}
	}
	if err := validator.ValidateCustom("x-option-value-max", v.Email, "50"); err != nil {
		return &validator.ValidationError{
			Field:   "Email",
			Rule:    "x-option-value-max",
			Message: err.Error(),
		}
	}

	// Кастомная валидация поля Phone
	if err := validator.ValidateCustom("x-option-absent", v.Phone, ""); err != nil {
		return &validator.ValidationError{
			Field:   "Phone",
			Rule:    "x-option-absent",
			Message: err.Error(),
		}
	}

	return nil
}
