// Code generated by elval-gen. DO NOT EDIT.
// Source: pet.go

package oa_discriminator

import (
	oa "github.com/arkannsk/elval/pkg/oa"
)

func (v *Pet) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
	}
	// Поле Type
	{
		prop := oa.Schema{}

		prop.Type = "string"

		prop.Example = "cat"

		schema.Properties["type"] = prop
	}
	// Поле Name
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}

	schema.Discriminator = &oa.Discriminator{
		PropertyName: "type",
		Mapping: map[string]string{
			"cat": "Cat",
			"dog": "Dog",
		},
	}

	return schema
}

func (v *Cat) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
	}
	// Поле Pet
	{
		prop := oa.Schema{}

		prop.Ref = "#/components/schemas/Pet"

		schema.Properties["pet"] = prop
	}
	// Поле Meows
	{
		prop := oa.Schema{}

		prop.Type = "boolean"

		prop.Example = true

		schema.Properties["meows"] = prop
	}

	return schema
}

func (v *Dog) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
	}
	// Поле Pet
	{
		prop := oa.Schema{}

		prop.Ref = "#/components/schemas/Pet"

		schema.Properties["pet"] = prop
	}
	// Поле BarkVolume
	{
		prop := oa.Schema{}

		prop.Type = "integer"

		prop.Example = 5

		schema.Properties["barkvolume"] = prop
	}

	return schema
}
