// Code generated by elval-gen. DO NOT EDIT.
// Source: pet.go

package oa_discriminator

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Pet) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Example = "cat"

		schema.Properties["type"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}

	schema.Discriminator = &oa.Discriminator{
		PropertyName: "type",
		Mapping: map[string]string{
			"cat": "Cat",
			"dog": "Dog",
		},
	}

	return schema
}

func (v *Pet) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_discriminator.Pet"
}

func (v *Cat) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/Pet"

		schema.Properties["pet"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "boolean"

		prop.Example = "true"

		schema.Properties["meows"] = prop
	}

	return schema
}

func (v *Cat) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_discriminator.Cat"
}

func (v *Dog) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/Pet"

		schema.Properties["pet"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Example = "5"

		schema.Properties["barkvolume"] = prop
	}

	return schema
}

func (v *Dog) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_discriminator.Dog"
}
