// Code generated by elval-gen. DO NOT EDIT.
// Source: common.go

package mixed

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *NoAnnotations) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["id"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}

	return schema
}

func (v *NoAnnotations) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/mixed.NoAnnotations"
}

func (v *Helper) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["code"] = prop
	}

	return schema
}

func (v *Helper) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/mixed.Helper"
}
