// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package mixed

import (
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Eq[string]("active"))
		return v
	}()

	QuantityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Quantity")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](100))
		return v
	}()

	PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Gt[float64](0))
		return v
	}()
)

// Validate проверяет структуру Product
func (v *Product) Validate() error {

	if err := StatusValidator.Validate(v.Status); err != nil {
		return err
	}

	if err := QuantityValidator.Validate(v.Quantity); err != nil {
		return err
	}

	if err := PriceValidator.Validate(v.Price); err != nil {
		return err
	}

	return nil
}
