// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package mixed

import (
	"context"
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	Product_StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Eq[string]("active"))
		return v
	}()

	Product_QuantityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Quantity")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](100))
		return v
	}()

	Product_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Gt[float64](0))
		return v
	}()
)

func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

func (v *Product) Validate() error {

	if err := Product_StatusValidator.Validate(v.Status); err != nil {
		return err
	}

	if err := Product_QuantityValidator.Validate(v.Quantity); err != nil {
		return err
	}

	if err := Product_PriceValidator.Validate(v.Price); err != nil {
		return err
	}
	return nil
}
