// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package mixed

import (
	"fmt"
	"github.com/arkannsk/elval/pkg/validator"
)

// Validate проверяет структуру Product
func (v *Product) Validate() error {
	var errs []error
	// Валидация поля Status

	{

		builder := validator.New[string]("Status")
		builder.AddRule(validator.Required[string]())
		builder.AddRule(validator.Eq("active"))
		if err := builder.Validate(v.Status); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Quantity

	{

		builder := validator.New[int]("Quantity")
		builder.AddRule(validator.Required[int]())
		builder.AddRule(validator.Min[int](1))
		builder.AddRule(validator.Max[int](100))
		if err := builder.Validate(v.Quantity); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Price

	{

		builder := validator.New[float64]("Price")
		builder.AddRule(validator.Gt[float64](0))
		if err := builder.Validate(v.Price); err != nil {
			errs = append(errs, err)
		}
	}

	if len(errs) > 0 {
		return fmt.Errorf("ошибки валидации: %v", errs)
	}
	return nil

}
