// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package mixed

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Product) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "status")

		schema.Properties["status"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Required = append(schema.Required, "quantity")
		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](100)

		schema.Properties["quantity"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Minimum = oa.Ptr[float64](0)
		prop.ExclusiveMinimum = true

		schema.Properties["price"] = prop
	}

	return schema
}

func (v *Product) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/mixed.Product"
}
