// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package mixed

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](2)
		prop.MaxLength = oa.Ptr[int64](50)

		schema.Properties["name"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		schema.Properties["email"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		schema.Properties["age"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/mixed.User"
}
