// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package mixed

import (
	"fmt"
	"github.com/arkannsk/elval/pkg/validator"
)

// Validate проверяет структуру User
func (v *User) Validate() error {
	var errs []error
	// Валидация поля Name

	{

		builder := validator.New[string]("Name")
		builder.AddRule(validator.Required[string]())
		builder.AddRule(validator.MinLen(2))
		builder.AddRule(validator.MaxLen(50))
		if err := builder.Validate(v.Name); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Email

	{

		builder := validator.New[string]("Email")
		builder.AddRule(validator.Required[string]())
		builder.AddRule(validator.Email())
		if err := builder.Validate(v.Email); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Age

	{

		builder := validator.New[int]("Age")
		builder.AddRule(validator.Min[int](18))
		builder.AddRule(validator.Max[int](120))
		if err := builder.Validate(v.Age); err != nil {
			errs = append(errs, err)
		}
	}

	if len(errs) > 0 {
		return fmt.Errorf("ошибки валидации: %v", errs)
	}
	return nil

}
