// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package mixed

import (
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		return v
	}()
)

func (v *User) Validate() error {

	if err := User_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err := User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	if err := User_AgeValidator.Validate(v.Age); err != nil {
		return err
	}
	return nil
}
