// Code generated by elval-gen. DO NOT EDIT.
// Source: url_validation.go

package url_validation

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Link) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "website")

		schema.Properties["website"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["blog"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "api")

		schema.Properties["api"] = prop
	}

	return schema
}

func (v *Link) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/url_validation.Link"
}

func (v *Profile) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "secureurl")

		schema.Properties["secureurl"] = prop
	}

	return schema
}

func (v *Profile) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/url_validation.Profile"
}

func (v *Config) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "anyurl")

		schema.Properties["anyurl"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "weburl")

		schema.Properties["weburl"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "databaseurl")

		schema.Properties["databaseurl"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["clickhouseurl"] = prop
	}

	return schema
}

func (v *Config) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/url_validation.Config"
}
