// Code generated by elval-gen. DO NOT EDIT.
// Source: url_validation.go

package url_validation

import (
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	Link_WebsiteValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Website")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.URL())
		return v
	}()

	Link_BlogValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Blog")
		v.AddRule(validator.URL())
		original := v
		v = validator.New[string]("Blog")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Link_APIValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("API")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.URL())
		v.AddRule(validator.Contains("api"))
		return v
	}()
)

func (v *Link) Validate() error {
	if err := Link_WebsiteValidator.Validate(v.Website); err != nil {
		return err
	}
	if err := Link_BlogValidator.Validate(v.Blog); err != nil {
		return err
	}
	if err := Link_APIValidator.Validate(v.API); err != nil {
		return err
	}
	return nil
}

var (
	Profile_SecureURLValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("SecureURL")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.HTTPURL())
		v.AddRule(validator.StartsWith("https://"))
		return v
	}()
)

func (v *Profile) Validate() error {
	if err := Profile_SecureURLValidator.Validate(v.SecureURL); err != nil {
		return err
	}
	return nil
}

var (
	Config_AnyURLValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("AnyURL")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.URL())
		return v
	}()

	Config_WebURLValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("WebURL")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.HTTPURL())
		return v
	}()

	Config_DatabaseURLValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("DatabaseURL")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.DSN())
		return v
	}()

	Config_ClickHouseURLValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ClickHouseURL")
		v.AddRule(validator.DSN())
		original := v
		v = validator.New[string]("ClickHouseURL")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *Config) Validate() error {
	if err := Config_AnyURLValidator.Validate(v.AnyURL); err != nil {
		return err
	}
	if err := Config_WebURLValidator.Validate(v.WebURL); err != nil {
		return err
	}
	if err := Config_DatabaseURLValidator.Validate(v.DatabaseURL); err != nil {
		return err
	}
	if err := Config_ClickHouseURLValidator.Validate(v.ClickHouseURL); err != nil {
		return err
	}
	return nil
}
