// Code generated by elval-gen. DO NOT EDIT.
// Source: rewrite.go

package rewrite

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *UploadRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Ref = "#/components/schemas/json.RawMessage"

		prop.Description = "JSON payload as a base64 encoded string"

		schema.Properties["payload"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["userid"] = prop
	}

	return schema
}

func (v *UploadRequest) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/rewrite.UploadRequest"
}
