// Code generated by elval-gen. DO NOT EDIT.
// Source: nested.go

package nested

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	Address_CityValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("City")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		return v
	}()

	Address_StreetValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Street")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(5))
		return v
	}()

	Address_ZipCodeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ZipCode")
		v.AddRule(validator.MatchRegexp("^[0-9]{5,6}$"))
		original := v
		v = validator.New[string]("ZipCode")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *Address) Decorate(ctx context.Context) error {

	return nil
}

func (v *Address) Validate() error {
	var err *errs.ValidationError

	if err = Address_CityValidator.Validate(v.City); err != nil {
		return err
	}

	if err = Address_StreetValidator.Validate(v.Street); err != nil {
		return err
	}

	if err = Address_ZipCodeValidator.Validate(v.ZipCode); err != nil {
		return err
	}
	return nil
}

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AddressValidator = func() *validator.FieldValidator[Address] {
		v := validator.New[Address]("Address")
		return v
	}()

	User_BillingAddressValidator = func() *validator.FieldValidator[Address] {
		v := validator.New[Address]("BillingAddress")
		original := v
		v = validator.New[Address]("BillingAddress")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	return nil
}

func (v *User) Validate() error {
	var err *errs.ValidationError

	if err = User_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err = User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	// Вложенная структура Address
	if err := v.Address.Validate(); err != nil {
		return &errs.ValidationError{
			Field:   "Address",
			Rule:    "nested",
			Message: "поле Address: " + err.Error(),
		}
	}

	// Указатель BillingAddress
	if v.BillingAddress != nil {
		val := *v.BillingAddress
		if err := User_BillingAddressValidator.Validate(val); err != nil {
			return &errs.ValidationError{
				Field:   "BillingAddress",
				Rule:    "nested",
				Message: "поле BillingAddress: " + err.Error(),
			}
		}
	}

	return nil
}

var (
	Company_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		return v
	}()
)

func (v *Company) Decorate(ctx context.Context) error {

	return nil
}

func (v *Company) Validate() error {
	var err *errs.ValidationError

	if err = Company_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	// Валидация слайса Addresses
	// Обязательный слайс
	if true && len(v.Addresses) == 0 {
		return &errs.ValidationError{
			Field:   "Addresses",
			Rule:    "required",
			Message: "поле Addresses обязательно",
		}
	}
	if len(v.Addresses) < 1 {
		return &errs.ValidationError{
			Field:   "Addresses",
			Rule:    "min",
			Message: "поле Addresses должно содержать минимум 1 элементов",
		}
	}
	// Валидация элементов слайса структур
	for _, item := range v.Addresses {
		if err := item.Validate(); err != nil {
			return &errs.ValidationError{
				Field:   "Addresses",
				Rule:    "nested",
				Message: "поле Addresses: " + err.Error(),
			}
		}
	}

	// Валидация слайса Users
	if len(v.Users) > 0 {
		// Валидация элементов слайса структур
		for _, item := range v.Users {
			if err := item.Validate(); err != nil {
				return &errs.ValidationError{
					Field:   "Users",
					Rule:    "nested",
					Message: "поле Users: " + err.Error(),
				}
			}
		}
	} else if false {
		return &errs.ValidationError{
			Field:   "Users",
			Rule:    "not-zero",
			Message: "поле Users не может быть пустым",
		}
	}

	return nil
}
