// Code generated by elval-gen. DO NOT EDIT.
// Source: nested.go

package nested

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	Address_CityValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("City")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		return v
	}()

	Address_StreetValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Street")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(5))
		return v
	}()

	Address_ZipCodeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ZipCode")
		v.AddRule(validator.MatchRegexp("^[0-9]{5,6}$"))
		original := v
		v = validator.New[string]("ZipCode")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()
)

var (
	Company_AddressesValidator = func() *validator.SliceValidator[Address] {
		v := validator.NewSliceValidator[Address]("Addresses")
		v.Required()
		v.Min(1)
		return v
	}()
	Company_UsersValidator = func() *validator.SliceValidator[User] {
		v := validator.NewSliceValidator[User]("Users")
		v.SkipIfEmpty()
		return v
	}()
)

func (v *Address) Validate() error {
	var err *errs.ValidationError
	if v.City == "" {
		return errs.NewValidationError("City", "required", "field is required")
	}
	if err = Address_CityValidator.Validate(v.City); err != nil {
		return err
	}
	if v.Street == "" {
		return errs.NewValidationError("Street", "required", "field is required")
	}
	if err = Address_StreetValidator.Validate(v.Street); err != nil {
		return err
	}
	if err = Address_ZipCodeValidator.Validate(v.ZipCode); err != nil {
		return err
	}
	return err
}

func (v *User) Validate() error {
	var err *errs.ValidationError
	if v.Name == "" {
		return errs.NewValidationError("Name", "required", "field is required")
	}
	if err = User_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	if v.Email == "" {
		return errs.NewValidationError("Email", "required", "field is required")
	}
	if err = User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}
	if nestedErr := v.Address.Validate(); nestedErr != nil {
		if validationErr, ok := nestedErr.(*errs.ValidationError); ok && validationErr != nil {
			return errs.NewValidationError("Address", "nested", "err: %v", validationErr)
		}
	}
	return err
}

func (v *Company) Validate() error {
	var err *errs.ValidationError
	if v.Name == "" {
		return errs.NewValidationError("Name", "required", "field is required")
	}
	if err = Company_AddressesValidator.Validate(v.Addresses); err != nil {
		return err
	}
	for _, item := range v.Addresses {
		if nestedErr := item.Validate(); nestedErr != nil {
			if validationErr, ok := nestedErr.(*errs.ValidationError); ok && validationErr != nil {
				return errs.NewValidationError("Addresses", "element",
					"err: %v", validationErr)
			}
		}
	}
	if err = Company_UsersValidator.Validate(v.Users); err != nil {
		return err
	}
	for _, item := range v.Users {
		if nestedErr := item.Validate(); nestedErr != nil {
			if validationErr, ok := nestedErr.(*errs.ValidationError); ok && validationErr != nil {
				return errs.NewValidationError("Users", "element",
					"err: %v", validationErr)
			}
		}
	}
	return err
}
