// Code generated by elval-gen. DO NOT EDIT.
// Source: nested.go

package nested

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Address) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "city")
		prop.MinLength = oa.Ptr[int64](2)

		schema.Properties["city"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "street")
		prop.MinLength = oa.Ptr[int64](5)

		schema.Properties["street"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = "^[0-9]{5,6}$"

		schema.Properties["zipcode"] = prop
	}

	return schema
}

func (v *Address) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/nested.Address"
}

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](2)

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/Address"

		schema.Properties["address"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/*Address"

		schema.Properties["billingaddress"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/nested.User"
}

func (v *Company) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Ref = "#/components/schemas//.Address"

		schema.Required = append(schema.Required, "addresses")
		prop.Minimum = oa.Ptr[float64](1)

		schema.Properties["addresses"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Ref = "#/components/schemas//.User"

		schema.Properties["users"] = prop
	}

	return schema
}

func (v *Company) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/nested.Company"
}
