// Code generated by elval-gen. DO NOT EDIT.
// Source: openapi.go

package openapi

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](3)
		prop.MaxLength = oa.Ptr[int64](50)

		prop.Description = "Full name of the user"
		prop.Title = "User Name"
		prop.Example = "John Doe"

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		prop.Format = "email"

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = `^\+?[0-9]{8,15}$`
		prop.Format = "phone"

		schema.Properties["phone"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/openapi.User"
}

func (v *Product) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "status")
		prop.Enum = []any{"active", "inactive", "archived"}

		prop.Description = "Product status"

		schema.Properties["status"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "number"

		schema.Required = append(schema.Required, "price")
		prop.Minimum = oa.Ptr[float64](0)
		prop.ExclusiveMinimum = true

		schema.Properties["price"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](1000)

		schema.Properties["quantity"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "code")
		prop.MinLength = oa.Ptr[int64](10)
		prop.MaxLength = oa.Ptr[int64](10)

		schema.Properties["code"] = prop
	}

	return schema
}

func (v *Product) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/openapi.Product"
}

func (v *Order) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "id")

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"
		prop.Format = "date-time"

		schema.Required = append(schema.Required, "createdat")

		schema.Properties["createdat"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		schema.Required = append(schema.Required, "items")
		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](100)

		schema.Properties["items"] = prop
	}

	return schema
}

func (v *Order) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/openapi.Order"
}
