// Code generated by elval-gen. DO NOT EDIT.
// Source: openapi.go

package openapi

import (
	"context"
	"github.com/arkannsk/elval/pkg/oa"
	"github.com/arkannsk/elval/pkg/validator"
	"time"
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(3))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		return v
	}()

	User_PhoneValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Phone")
		v.AddRule(validator.Phone())
		original := v
		v = validator.New[string]("Phone")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

// Decorate применяет декораторы к структуре User
func (v *User) Decorate(ctx context.Context) error {

	return nil
}

// Validate проверяет структуру User
func (v *User) Validate() error {

	if err := User_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err := User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	if err := User_AgeValidator.Validate(v.Age); err != nil {
		return err
	}

	if err := User_PhoneValidator.Validate(v.Phone); err != nil {
		return err
	}
	return nil
}

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 4),
		Required:   make([]string, 0, 4),
	}
	{
		prop := oa.Schema{}
		prop.Type = "string"
		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](3)
		prop.MaxLength = oa.Ptr[int64](50)
		prop.Title = "User Name"
		prop.Description = "Full name of the user"
		prop.Example = "John Doe"
		schema.Properties["name"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "string"
		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`
		prop.Format = "email"
		prop.Format = "email"
		schema.Properties["email"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "integer"
		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)
		schema.Properties["age"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "string"
		prop.Pattern = `^\+?[0-9]{8,15}$`
		prop.Format = "phone"
		schema.Properties["phone"] = prop
	}
	return schema
}

var (
	Product_StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Enum[string]("active", "inactive", "archived"))
		return v
	}()

	Product_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Required[float64]())
		v.AddRule(validator.Gt[float64](0))
		return v
	}()

	Product_QuantityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Quantity")
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](1000))
		original := v
		v = validator.New[int]("Quantity")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Product_CodeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Code")
		v.AddRule(validator.Required[string]())
		return v
	}()
)

// Decorate применяет декораторы к структуре Product
func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

// Validate проверяет структуру Product
func (v *Product) Validate() error {

	if err := Product_StatusValidator.Validate(v.Status); err != nil {
		return err
	}

	if err := Product_PriceValidator.Validate(v.Price); err != nil {
		return err
	}

	if err := Product_QuantityValidator.Validate(v.Quantity); err != nil {
		return err
	}

	if err := Product_CodeValidator.Validate(v.Code); err != nil {
		return err
	}
	return nil
}

func (v *Product) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 4),
		Required:   make([]string, 0, 4),
	}
	{
		prop := oa.Schema{}
		prop.Type = "string"
		schema.Required = append(schema.Required, "status")
		prop.Enum = []interface{}{"active", "inactive", "archived"}
		prop.Description = "Product status"
		schema.Properties["status"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "number"
		schema.Required = append(schema.Required, "price")
		prop.Minimum = oa.Ptr[float64](0)
		prop.ExclusiveMinimum = true
		schema.Properties["price"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "integer"
		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](1000)
		schema.Properties["quantity"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "string"
		schema.Required = append(schema.Required, "code")
		prop.MinLength = oa.Ptr[int64](10)
		prop.MaxLength = oa.Ptr[int64](10)
		schema.Properties["code"] = prop
	}
	return schema
}

var (
	Order_IDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ID")
		v.AddRule(validator.Required[string]())
		return v
	}()

	Order_CreatedAtValidator = func() *validator.FieldValidator[time.Time] {
		v := validator.New[time.Time]("CreatedAt")
		v.AddRule(validator.Required[time.Time]())
		v.AddRule(validator.Before("2006-01-02", "2025-12-31"))
		v.AddRule(validator.After("2006-01-02", "2020-01-01"))
		return v
	}()
)

// Decorate применяет декораторы к структуре Order
func (v *Order) Decorate(ctx context.Context) error {

	return nil
}

// Validate проверяет структуру Order
func (v *Order) Validate() error {

	if err := Order_IDValidator.Validate(v.ID); err != nil {
		return err
	}

	if err := Order_CreatedAtValidator.Validate(v.CreatedAt); err != nil {
		return err
	}

	// Валидация слайса Items
	// Обязательный слайс
	if true && len(v.Items) == 0 {
		return &validator.ValidationError{
			Field:   "Items",
			Rule:    "required",
			Message: "поле Items обязательно",
		}
	}
	if len(v.Items) < 1 {
		return &validator.ValidationError{
			Field:   "Items",
			Rule:    "min",
			Message: "поле Items должно содержать минимум 1 элементов",
		}
	}
	if len(v.Items) > 100 {
		return &validator.ValidationError{
			Field:   "Items",
			Rule:    "max",
			Message: "поле Items должно содержать максимум 100 элементов",
		}
	}

	return nil
}

func (v *Order) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 3),
		Required:   make([]string, 0, 3),
	}
	{
		prop := oa.Schema{}
		prop.Type = "string"
		schema.Required = append(schema.Required, "id")
		schema.Properties["id"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "string"
		prop.Format = "date-time"
		schema.Required = append(schema.Required, "createdat")
		schema.Properties["createdat"] = prop
	}
	{
		prop := oa.Schema{}
		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Type = "string"
		schema.Required = append(schema.Required, "items")
		prop.MinLength = oa.Ptr[int64](1)
		prop.MaxLength = oa.Ptr[int64](100)
		schema.Properties["items"] = prop
	}
	return schema
}
