// Code generated by elval-gen. DO NOT EDIT.
// Source: openapi.go

package openapi

import (
	"github.com/arkannsk/elval/pkg/oa"
)

// OaSchema возвращает OpenAPI схему для структуры User
func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 4),
		Required:   make([]string, 0, 4),
	}
	// Поле Name
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](3)
		prop.MaxLength = oa.Ptr[int64](50)

		prop.Title = "User Name"
		prop.Description = "Full name of the user"
		prop.Example = "John Doe"

		schema.Properties["name"] = prop
	}
	// Поле Email
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		prop.Format = "email"

		schema.Properties["email"] = prop
	}
	// Поле Age
	{
		prop := oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		schema.Properties["age"] = prop
	}
	// Поле Phone
	{
		prop := oa.Schema{}

		prop.Type = "string"

		prop.Pattern = `^\+?[0-9]{8,15}$`
		prop.Format = "phone"

		schema.Properties["phone"] = prop
	}
	return schema
}

// OaSchema возвращает OpenAPI схему для структуры Product
func (v *Product) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 4),
		Required:   make([]string, 0, 4),
	}
	// Поле Status
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "status")
		prop.Enum = []interface{}{"active", "inactive", "archived"}

		prop.Description = "Product status"

		schema.Properties["status"] = prop
	}
	// Поле Price
	{
		prop := oa.Schema{}

		prop.Type = "number"

		schema.Required = append(schema.Required, "price")
		prop.Minimum = oa.Ptr[float64](0)
		prop.ExclusiveMinimum = true

		schema.Properties["price"] = prop
	}
	// Поле Quantity
	{
		prop := oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](1000)

		schema.Properties["quantity"] = prop
	}
	// Поле Code
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "code")
		prop.MinLength = oa.Ptr[int64](10)
		prop.MaxLength = oa.Ptr[int64](10)

		schema.Properties["code"] = prop
	}
	return schema
}

// OaSchema возвращает OpenAPI схему для структуры Order
func (v *Order) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 3),
		Required:   make([]string, 0, 3),
	}
	// Поле ID
	{
		prop := oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "id")

		schema.Properties["id"] = prop
	}
	// Поле CreatedAt
	{
		prop := oa.Schema{}

		prop.Type = "string"
		prop.Format = "date-time"

		schema.Required = append(schema.Required, "createdat")

		schema.Properties["createdat"] = prop
	}
	// Поле Items
	{
		prop := oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Type = "string"

		schema.Required = append(schema.Required, "items")
		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](100)

		schema.Properties["items"] = prop
	}
	return schema
}
