// Code generated by elval-gen. DO NOT EDIT.
// Source: openapi.go

package openapi

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
	"time"
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(3))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		return v
	}()

	User_PhoneValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Phone")
		v.AddRule(validator.Phone())
		original := v
		v = validator.New[string]("Phone")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

var (
	Product_StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Enum[string]("active", "inactive", "archived"))
		return v
	}()

	Product_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Required[float64]())
		v.AddRule(validator.Gt[float64](0))
		return v
	}()

	Product_QuantityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Quantity")
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](1000))
		original := v
		v = validator.New[int]("Quantity")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Product_CodeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Code")
		v.AddRule(validator.Required[string]())
		return v
	}()
)

var (
	Order_IDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ID")
		v.AddRule(validator.Required[string]())
		return v
	}()

	Order_CreatedAtValidator = func() *validator.FieldValidator[time.Time] {
		v := validator.New[time.Time]("CreatedAt")
		v.AddRule(validator.Required[time.Time]())
		v.AddRule(validator.Before("2006-01-02", "2025-12-31"))
		v.AddRule(validator.After("2006-01-02", "2020-01-01"))
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	return nil
}

func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

func (v *Order) Decorate(ctx context.Context) error {

	return nil
}

func (v *User) Validate() error {
	var err *errs.ValidationError
	if err = User_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	if err = User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}
	if err = User_AgeValidator.Validate(v.Age); err != nil {
		return err
	}
	if err = User_PhoneValidator.Validate(v.Phone); err != nil {
		return err
	}
	return nil
}

func (v *Product) Validate() error {
	var err *errs.ValidationError
	if err = Product_StatusValidator.Validate(v.Status); err != nil {
		return err
	}
	if err = Product_PriceValidator.Validate(v.Price); err != nil {
		return err
	}
	if err = Product_QuantityValidator.Validate(v.Quantity); err != nil {
		return err
	}
	if err = Product_CodeValidator.Validate(v.Code); err != nil {
		return err
	}
	return nil
}

func (v *Order) Validate() error {
	var err *errs.ValidationError
	if err = Order_IDValidator.Validate(v.ID); err != nil {
		return err
	}
	if err = Order_CreatedAtValidator.Validate(v.CreatedAt); err != nil {
		return err
	}

	// Валидация слайса Items
	// Обязательный слайс
	if true && len(v.Items) == 0 {
		return &errs.ValidationError{
			Field:   "Items",
			Rule:    "required",
			Message: "поле Items обязательно",
		}
	}
	if len(v.Items) < 1 {
		return &errs.ValidationError{
			Field:   "Items",
			Rule:    "min",
			Message: "поле Items должно содержать минимум 1 элементов",
		}
	}
	if len(v.Items) > 100 {
		return &errs.ValidationError{
			Field:   "Items",
			Rule:    "max",
			Message: "поле Items должно содержать максимум 100 элементов",
		}
	}

	return nil
}
