// Code generated by elval-gen. DO NOT EDIT.
// Source: address.go

package user

import (
	oa "github.com/arkannsk/elval/pkg/oa"
)

func (v *Address) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		prop.Example = "Tverskaya 1"

		schema.Properties["street"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		prop.Example = "123456"

		schema.Properties["zipcode"] = prop
	}

	return schema
}

func (v *Address) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_unique_refs/user.Address"
}
