// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package user

import (
	oa "github.com/arkannsk/elval/pkg/oa"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		prop.Example = "user-123"

		schema.Properties["id"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Type = "string"

		prop.Example = "john@example.com"

		schema.Properties["email"] = prop
	}
	{
		prop := oa.Schema{}

		prop.Example = `{"street":"Lenina 10","zipCode":"101000"}`

		schema.Properties["address"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_unique_refs/user.User"
}
