// Code generated by elval-gen. DO NOT EDIT.
// Source: event.go

package local_generic

import (
	"context"
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
	"time"
)

var (
	Event_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		return v
	}()

	Event_StartDateValidator = func() *validator.FieldValidator[time.Time] {
		v := validator.New[time.Time]("StartDate")
		v.AddRule(validator.Required[time.Time]())
		v.AddRule(validator.After("2006-01-02", "2020-01-01"))
		v.AddRule(validator.Before("2006-01-02", "2030-01-01"))
		return v
	}()

	Event_EndDateValidator = func() *validator.FieldValidator[time.Time] {
		v := validator.New[time.Time]("EndDate")
		v.AddRule(validator.Required[time.Time]())
		v.AddRule(validator.After("2006-01-02", "2020-01-01"))
		return v
	}()
)

func (v *Event) Decorate(ctx context.Context) error {

	return nil
}

func (v *Event) Validate() error {
	var err *errs.ValidationError
	if err = Event_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	if !elval.Unwrap[time.Time](v.StartDate).IsPresent() {
		return &errs.ValidationError{Field: "StartDate", Rule: "required", Message: "not present"}
	}
	if wrapper := elval.Unwrap[time.Time](v.StartDate); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = Event_StartDateValidator.Validate(val); err != nil {
			return err
		}
	}
	if !elval.Unwrap[time.Time](v.EndDate).IsPresent() {
		return &errs.ValidationError{Field: "EndDate", Rule: "required", Message: "not present"}
	}
	if wrapper := elval.Unwrap[time.Time](v.EndDate); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = Event_EndDateValidator.Validate(val); err != nil {
			return err
		}
	}
	return nil
}
