// Code generated by elval-gen. DO NOT EDIT.
// Source: event.go

package local_generic

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Event) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}

	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "startdate")

		schema.Properties["startdate"] = prop
	}

	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "enddate")

		schema.Properties["enddate"] = prop
	}

	return schema
}

func (v *Event) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/local_generic.Event"
}
