// Code generated by elval-gen. DO NOT EDIT.
// Source: option_user.go

package local_generic

import (
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	UserProfile_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MatchRegexp("^[a-z0-9._%+-]+"))
		return v
	}()

	UserProfile_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		original := v
		v = validator.New[int]("Age")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

var ()

func (v *UserProfile) Validate() error {
	var err *errs.ValidationError
	if !elval.Unwrap[string](v.Email).IsPresent() {
		return errs.NewValidationError("Email", "required", "not present")
	}
	if wrapper := elval.Unwrap[string](v.Email); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = UserProfile_EmailValidator.Validate(val); err != nil {
			return err
		}
	}
	if wrapper := elval.Unwrap[int](v.Age); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = UserProfile_AgeValidator.Validate(val); err != nil {
			return err
		}
	}
	if !elval.Unwrap[UserMeta](v.Metadata).IsPresent() {
		return errs.NewValidationError("Metadata", "required", "not present")
	}
	return err
}

func (v *UserMeta) Validate() error {
	var err *errs.ValidationError
	if v.DisplayName == "" {
		return errs.NewValidationError("DisplayName", "required", "field is required")
	}
	return err
}
