// Code generated by elval-gen. DO NOT EDIT.
// Source: option_user.go

package local_generic

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *UserProfile) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "email")

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "metadata")

		schema.Properties["metadata"] = prop
	}

	return schema
}

func (v *UserProfile) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/local_generic.UserProfile"
}

func (v *UserMeta) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "displayname")

		schema.Properties["displayname"] = prop
	}

	return schema
}

func (v *UserMeta) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/local_generic.UserMeta"
}
