// Code generated by elval-gen. DO NOT EDIT.
// Source: option_user.go

package local_generic

import (
	"context"
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	UserProfile_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		return v
	}()

	UserProfile_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		original := v
		v = validator.New[int]("Age")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	UserProfile_MetadataValidator = func() *validator.FieldValidator[UserMeta] {
		v := validator.New[UserMeta]("Metadata")
		v.AddRule(validator.Required[UserMeta]())
		return v
	}()
)

var (
	UserMeta_DisplayNameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("DisplayName")
		v.AddRule(validator.Required[string]())
		return v
	}()
)

func (v *UserProfile) Decorate(ctx context.Context) error {

	return nil
}

func (v *UserMeta) Decorate(ctx context.Context) error {

	return nil
}

func (v *UserProfile) Validate() error {
	var err *errs.ValidationError
	if !elval.Unwrap[string](v.Email).IsPresent() {
		return &errs.ValidationError{Field: "Email", Rule: "required", Message: "not present"}
	}
	if wrapper := elval.Unwrap[string](v.Email); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = UserProfile_EmailValidator.Validate(val); err != nil {
			return err
		}
	}
	if wrapper := elval.Unwrap[int](v.Age); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = UserProfile_AgeValidator.Validate(val); err != nil {
			return err
		}
	}
	if !elval.Unwrap[UserMeta](v.Metadata).IsPresent() {
		return &errs.ValidationError{Field: "Metadata", Rule: "required", Message: "not present"}
	}
	if wrapper := elval.Unwrap[UserMeta](v.Metadata); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = UserProfile_MetadataValidator.Validate(val); err != nil {
			return err
		}
	}
	return nil
}

func (v *UserMeta) Validate() error {
	var err *errs.ValidationError
	if err = UserMeta_DisplayNameValidator.Validate(v.DisplayName); err != nil {
		return err
	}
	return nil
}
