// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package local_generic

import (
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	Review_CommentValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Comment")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(3))
		v.AddRule(validator.MaxLen(500))
		return v
	}()

	Review_RatingValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Rating")
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](5))
		original := v
		v = validator.New[int]("Rating")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

var ()

func (v *Review) Validate() error {
	var err *errs.ValidationError
	if v.Comment == "" {
		return errs.NewValidationError("Comment", "required", "field is required")
	}
	if err = Review_CommentValidator.Validate(v.Comment); err != nil {
		return err
	}
	{
		wrapper := elval.UnwrapGeneric[int](v.Rating)
		if wrapper.IsPresent() {
			val, _ := wrapper.Value()
			if err = Review_RatingValidator.Validate(val); err != nil {
				return err
			}
		}
	}
	return err
}

func (v *Product) Validate() error {
	var err *errs.ValidationError
	if v.Name == "" {
		return errs.NewValidationError("Name", "required", "field is required")
	}
	for _, item := range v.Reviews {
		wrapper := elval.UnwrapGeneric[Review](item)
		if wrapper.IsPresent() {
			val, _ := wrapper.Value()
			if nestedErr := val.Validate(); nestedErr != nil {
				if validationErr, ok := nestedErr.(*errs.ValidationError); ok && validationErr != nil {
					return errs.NewValidationError("Reviews", "element", "err: %v", validationErr)
				}
			}
		}
	}
	return err
}
