// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package local_generic

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Review) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "comment")
		prop.MinLength = oa.Ptr[int64](3)
		prop.MaxLength = oa.Ptr[int64](500)

		schema.Properties["comment"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](5)

		schema.Properties["rating"] = prop
	}

	return schema
}

func (v *Review) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/local_generic.Review"
}

func (v *Product) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}
		prop.Items.Ref = "#/components/schemas/github.com/arkannsk/elval/test/integration/local_generic.Review"

		schema.Properties["reviews"] = prop
	}

	return schema
}

func (v *Product) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/local_generic.Product"
}
