// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package local_generic

import (
	"context"
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	Review_CommentValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Comment")
		v.AddRule(validator.Required[string]())
		return v
	}()

	Review_RatingValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Rating")
		original := v
		v = validator.New[int]("Rating")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

var (
	Product_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		return v
	}()

	Product_ReviewsValidator = func() *validator.FieldValidator[Review] {
		v := validator.New[Review]("Reviews")
		original := v
		v = validator.New[Review]("Reviews")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *Review) Decorate(ctx context.Context) error {

	return nil
}

func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

func (v *Review) Validate() error {
	var err *errs.ValidationError
	if err = Review_CommentValidator.Validate(v.Comment); err != nil {
		return err
	}
	if wrapper := elval.Unwrap[int](v.Rating); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = Review_RatingValidator.Validate(val); err != nil {
			return err
		}
	}
	return nil
}

func (v *Product) Validate() error {
	var err *errs.ValidationError
	if err = Product_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	for _, item := range v.Reviews {
		if wrapper := elval.Unwrap[Review](item); wrapper.IsPresent() {
			val, _ := wrapper.Value()
			if err = Product_ReviewsValidator.Validate(val); err != nil {
				return err
			}
		}
	}
	return nil
}
