// Code generated by elval-gen. DO NOT EDIT.
// Source: settings.go

package local_generic

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	UserSettings_ThemeValidator = func() *validator.FieldValidator[Theme] {
		v := validator.New[Theme]("Theme")
		v.AddRule(validator.Required[Theme]())
		return v
	}()

	UserSettings_PrimaryColorValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("PrimaryColor")
		return v
	}()

	UserSettings_NotificationEmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("NotificationEmail")
		original := v
		v = validator.New[string]("NotificationEmail")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *UserSettings) Decorate(ctx context.Context) error {

	return nil
}

func (v *UserSettings) Validate() error {
	var err *errs.ValidationError
	if err = UserSettings_ThemeValidator.Validate(v.Theme); err != nil {
		return err
	}
	if val, ok := v.PrimaryColor.Value(); ok {
		if err = UserSettings_PrimaryColorValidator.Validate(val); err != nil {
			return err
		}
	}
	if val, ok := v.NotificationEmail.Value(); ok {
		if err = UserSettings_NotificationEmailValidator.Validate(val); err != nil {
			return err
		}
	}
	return nil
}
