// Code generated by elval-gen. DO NOT EDIT.
// Source: settings.go

package local_generic

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *UserSettings) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "theme")
		prop.Enum = []any{"light", "dark", "custom"}

		schema.Properties["theme"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Pattern = "^#[0-9A-Fa-f]{6}$"

		schema.Properties["primarycolor"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		schema.Properties["notificationemail"] = prop
	}

	return schema
}

func (v *UserSettings) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/local_generic.UserSettings"
}
