// Code generated by elval-gen. DO NOT EDIT.
// Source: settings.go

package local_generic

import (
	"context"
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	UserSettings_ThemeValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Theme")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Enum[string]("light", "dark", "custom"))
		return v
	}()

	UserSettings_PrimaryColorValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("PrimaryColor")
		v.AddRule(validator.MatchRegexp("^#[0-9A-Fa-f]{6}$"))
		return v
	}()

	UserSettings_NotificationEmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("NotificationEmail")
		v.AddRule(validator.Email())
		original := v
		v = validator.New[string]("NotificationEmail")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *UserSettings) Decorate(ctx context.Context) error {

	return nil
}

func (v *UserSettings) Validate() error {
	var err *errs.ValidationError
	if err = UserSettings_ThemeValidator.Validate((string)(v.Theme)); err != nil {
		return err
	}
	if wrapper := elval.Unwrap[string](v.PrimaryColor); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = UserSettings_PrimaryColorValidator.Validate(val); err != nil {
			return err
		}
	}
	if wrapper := elval.Unwrap[string](v.NotificationEmail); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = UserSettings_NotificationEmailValidator.Validate(val); err != nil {
			return err
		}
	}
	return nil
}
