// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package main

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 5),
		Required:   make([]string, 0, 5),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "name")
		prop.Minimum = oa.Ptr[float64](3)
		prop.Maximum = oa.Ptr[float64](50)

		schema.Properties["name"] = prop
	}

	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		schema.Properties["email"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		schema.Properties["age"] = prop
	}

	{
		prop := &oa.Schema{}

		schema.Properties["password"] = prop
	}

	{
		prop := &oa.Schema{}

		schema.Required = append(schema.Required, "tag")
		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](10)

		schema.Properties["tag"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/mo_option.User"
}
