// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package main

import (
	"context"
	elval "github.com/arkannsk/elval"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(3))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		original := v
		v = validator.New[int]("Age")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	User_PasswordValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Password")
		v.AddRule(func(value string) *errs.ValidationError {
			return validator.ValidateCustom("x-strong-password", value, "")
		})
		original := v
		v = validator.New[string]("Password")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	User_TagValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Tag")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(1))
		v.AddRule(validator.MaxLen(10))
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	return nil
}

func (v *User) Validate() error {
	var err *errs.ValidationError
	if !elval.Unwrap[string](v.Name).IsPresent() {
		return &errs.ValidationError{Field: "Name", Rule: "required", Message: errs.ErrRequired.Message}
	}
	if wrapper := elval.Unwrap[string](v.Name); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = User_NameValidator.Validate(val); err != nil {
			return err
		}
	}
	if !elval.Unwrap[string](v.Email).IsPresent() {
		return &errs.ValidationError{Field: "Email", Rule: "required", Message: errs.ErrRequired.Message}
	}
	if wrapper := elval.Unwrap[string](v.Email); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = User_EmailValidator.Validate(val); err != nil {
			return err
		}
	}
	if wrapper := elval.Unwrap[int](v.Age); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = User_AgeValidator.Validate(val); err != nil {
			return err
		}
	}
	if wrapper := elval.Unwrap[string](v.Password); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = User_PasswordValidator.Validate(val); err != nil {
			return err
		}
		if cErr := validator.ValidateCustom("x-strong-password", val, ""); cErr != nil {
			return cErr
		}
	}
	if !elval.Unwrap[string](v.Tag).IsPresent() {
		return &errs.ValidationError{Field: "Tag", Rule: "required", Message: errs.ErrRequired.Message}
	}
	if wrapper := elval.Unwrap[string](v.Tag); wrapper.IsPresent() {
		val, _ := wrapper.Value()
		if err = User_TagValidator.Validate(val); err != nil {
			return err
		}
	}
	return nil
}
