// Code generated by elval-gen. DO NOT EDIT.
// Source: multi.go

package multi

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		return v
	}()
)

var (
	Product_StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Eq[string]("active"))
		return v
	}()

	Product_QuantityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Quantity")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](100))
		return v
	}()

	Product_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Gt[float64](0))
		return v
	}()
)

var (
	Order_UserIDValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("UserID")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](1))
		return v
	}()

	Order_TotalValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Total")
		v.AddRule(validator.Min[float64](0.01))
		original := v
		v = validator.New[float64]("Total")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Order_ItemsValidator = func() *validator.SliceValidator[string] {
		v := validator.NewSliceValidator[string]("Items")
		v.SkipIfEmpty()
		v.Min(1)
		v.Max(100)
		return v
	}()
)

func (v *User) Validate() error {
	var err *errs.ValidationError
	if v.Name == "" {
		return errs.NewValidationError("Name", "required", "field is required")
	}
	if err = User_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	if v.Email == "" {
		return errs.NewValidationError("Email", "required", "field is required")
	}
	if err = User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}
	if err = User_AgeValidator.Validate(v.Age); err != nil {
		return err
	}
	return err
}

func (v *Product) Validate() error {
	var err *errs.ValidationError
	if v.Status == "" {
		return errs.NewValidationError("Status", "required", "field is required")
	}
	if err = Product_StatusValidator.Validate(v.Status); err != nil {
		return err
	}
	if v.Quantity == 0 {
		return errs.NewValidationError("Quantity", "required", "field is required")
	}
	if err = Product_QuantityValidator.Validate(v.Quantity); err != nil {
		return err
	}
	if err = Product_PriceValidator.Validate(v.Price); err != nil {
		return err
	}
	return err
}

func (v *Order) Validate() error {
	var err *errs.ValidationError
	if v.ID == "" {
		return errs.NewValidationError("ID", "required", "field is required")
	}
	if v.UserID == 0 {
		return errs.NewValidationError("UserID", "required", "field is required")
	}
	if err = Order_UserIDValidator.Validate(v.UserID); err != nil {
		return err
	}
	if err = Order_TotalValidator.Validate(v.Total); err != nil {
		return err
	}
	if err = Order_ItemsValidator.Validate(v.Items); err != nil {
		return err
	}
	return err
}
