// Code generated by elval-gen. DO NOT EDIT.
// Source: multi.go

package multi

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](2)
		prop.MaxLength = oa.Ptr[int64](50)

		schema.Properties["name"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		schema.Properties["email"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		schema.Properties["age"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/multi.User"
}

func (v *Product) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 3),
		Required:   make([]string, 0, 3),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "status")

		schema.Properties["status"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Required = append(schema.Required, "quantity")
		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](100)

		schema.Properties["quantity"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Minimum = oa.Ptr[float64](0)
		prop.ExclusiveMinimum = true

		schema.Properties["price"] = prop
	}

	return schema
}

func (v *Product) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/multi.Product"
}

func (v *Order) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "id")

		schema.Properties["id"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Required = append(schema.Required, "userid")
		prop.Minimum = oa.Ptr[float64](1)

		schema.Properties["userid"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Minimum = oa.Ptr[float64](0.01)

		schema.Properties["total"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](100)

		schema.Properties["items"] = prop
	}

	return schema
}

func (v *Order) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/multi.Order"
}

func (v *Config) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["host"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["port"] = prop
	}

	return schema
}

func (v *Config) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/multi.Config"
}
