// Code generated by elval-gen. DO NOT EDIT.
// Source: multi.go

package multi

import (
	"context"
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	User_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	User_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	User_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	return nil
}

func (v *User) Validate() error {

	if err := User_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err := User_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	if err := User_AgeValidator.Validate(v.Age); err != nil {
		return err
	}
	return nil
}

var (
	Product_StatusValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Status")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Eq[string]("active"))
		return v
	}()

	Product_QuantityValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Quantity")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](1))
		v.AddRule(validator.Max[int](100))
		return v
	}()

	Product_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Gt[float64](0))
		return v
	}()
)

func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

func (v *Product) Validate() error {

	if err := Product_StatusValidator.Validate(v.Status); err != nil {
		return err
	}

	if err := Product_QuantityValidator.Validate(v.Quantity); err != nil {
		return err
	}

	if err := Product_PriceValidator.Validate(v.Price); err != nil {
		return err
	}
	return nil
}

var (
	Order_IDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ID")
		v.AddRule(validator.Required[string]())
		return v
	}()

	Order_UserIDValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("UserID")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](1))
		return v
	}()

	Order_TotalValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Total")
		v.AddRule(validator.Min[float64](0.01))
		original := v
		v = validator.New[float64]("Total")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *Order) Decorate(ctx context.Context) error {

	return nil
}

func (v *Order) Validate() error {

	if err := Order_IDValidator.Validate(v.ID); err != nil {
		return err
	}

	if err := Order_UserIDValidator.Validate(v.UserID); err != nil {
		return err
	}

	if err := Order_TotalValidator.Validate(v.Total); err != nil {
		return err
	}

	// Валидация слайса Items
	if len(v.Items) > 0 {
		if len(v.Items) < 1 {
			return &validator.ValidationError{
				Field:   "Items",
				Rule:    "min",
				Message: "поле Items должно содержать минимум 1 элементов",
			}
		}
		if len(v.Items) > 100 {
			return &validator.ValidationError{
				Field:   "Items",
				Rule:    "max",
				Message: "поле Items должно содержать максимум 100 элементов",
			}
		}
	} else if false {
		return &validator.ValidationError{
			Field:   "Items",
			Rule:    "not-zero",
			Message: "поле Items не может быть пустым",
		}
	}

	return nil
}
