// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package main

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	Product_ColorValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Color")
		v.AddRule(validator.Required[string]())
		v.AddRule(func(value string) *errs.ValidationError {
			return validator.ValidateCustom("x-color", value, "")
		})
		return v
	}()

	Product_CountValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Count")
		v.AddRule(validator.Required[int]())
		v.AddRule(func(value int) *errs.ValidationError {
			return validator.ValidateCustom("x-even", value, "")
		})
		return v
	}()

	Product_ScoreValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Score")
		v.AddRule(func(value int) *errs.ValidationError {
			return validator.ValidateCustom("x-between", value, "10")
		})
		return v
	}()

	Product_DescriptionValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Description")
		v.AddRule(func(value string) *errs.ValidationError {
			return validator.ValidateCustom("x-contains", value, "important")
		})
		return v
	}()
)

func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

func (v *Product) Validate() error {
	var err *errs.ValidationError
	if err = Product_ColorValidator.Validate(v.Color); err != nil {
		return err
	}
	if err = Product_CountValidator.Validate(v.Count); err != nil {
		return err
	}
	if err = Product_ScoreValidator.Validate(v.Score); err != nil {
		return err
	}
	if err = Product_DescriptionValidator.Validate(v.Description); err != nil {
		return err
	}
	return nil
}
