// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package main

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	"github.com/arkannsk/elval/pkg/validator"
)

var ()

func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

func (v *Product) Validate() error {
	var err *errs.ValidationError
	return nil
}
