// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package main

import (
	"context"
	"github.com/arkannsk/elval/pkg/validator"
)

var ()

func (v *Product) Decorate(ctx context.Context) error {

	return nil
}

func (v *Product) Validate() error {

	// Кастомная валидация поля Color
	if err := validator.ValidateCustom("x-color", v.Color, ""); err != nil {
		return &validator.ValidationError{
			Field:   "Color",
			Rule:    "x-color",
			Message: err.Error(),
		}
	}

	// Кастомная валидация поля Count
	if err := validator.ValidateCustom("x-even", v.Count, ""); err != nil {
		return &validator.ValidationError{
			Field:   "Count",
			Rule:    "x-even",
			Message: err.Error(),
		}
	}

	// Кастомная валидация поля Score
	if err := validator.ValidateCustom("x-between", v.Score, "10"); err != nil {
		return &validator.ValidationError{
			Field:   "Score",
			Rule:    "x-between",
			Message: err.Error(),
		}
	}

	// Кастомная валидация поля Description
	if err := validator.ValidateCustom("x-contains", v.Description, "important"); err != nil {
		return &validator.ValidationError{
			Field:   "Description",
			Rule:    "x-contains",
			Message: err.Error(),
		}
	}

	return nil
}
