// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package main

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Product) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "color")

		schema.Properties["color"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Required = append(schema.Required, "count")

		schema.Properties["count"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Properties["score"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["description"] = prop
	}

	return schema
}

func (v *Product) GlobalRef() string {
	return "github.com/arkannsk/elval/examples/custom.Product"
}
