// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package integration

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Node) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "value")
		prop.MaxLength = oa.Ptr[int64](50)

		schema.Properties["value"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/*Node"

		schema.Properties["next"] = prop
	}

	return schema
}

func (v *Node) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/recursive.Node"
}
