// Code generated by elval-gen. DO NOT EDIT.
// Source: product.go

package integration

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	Node_ValueValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Value")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MaxLen(50))
		return v
	}()
)

func (v *Node) Validate() error {
	var err *errs.ValidationError
	if v.Value == "" {
		return errs.NewValidationError("Value", "required", "field is required")
	}
	if err = Node_ValueValidator.Validate(v.Value); err != nil {
		return err
	}
	if v.Next != nil {
		if nestedErr := v.Next.Validate(); nestedErr != nil {
			if validationErr, ok := nestedErr.(*errs.ValidationError); ok && validationErr != nil {
				return errs.NewValidationError("Next", "nested", "err: %v", validationErr)
			}
		}
	}
	return err
}
