// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package main

import (
	"context"
	"github.com/arkannsk/elval/pkg/validator"
	"github.com/google/uuid"
	"net/http"
	"os"
	"time"
)

var (
	User_IDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ID")
		v.AddRule(validator.Required[string]())
		return v
	}()

	User_RoleValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Role")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Enum[string]("admin", "user", "guest"))
		return v
	}()

	User_EnvironmentValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Environment")
		return v
	}()

	User_CreatedAtValidator = func() *validator.FieldValidator[time.Time] {
		v := validator.New[time.Time]("CreatedAt")
		return v
	}()

	User_RequestIDValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("RequestID")
		return v
	}()
)

func (v *User) Decorate(ctx context.Context) error {

	if val := ctx.Value("user_id"); val != nil {
		if str, ok := val.(string); ok {
			v.ID = str
		}
	}

	if r := ctx.Value("http.request"); r != nil {
		if req, ok := r.(*http.Request); ok {
			v.Role = req.Header.Get("X-User-Role")
		}
	}

	v.Environment = os.Getenv("APP_ENV")

	v.CreatedAt = time.Now()

	v.RequestID = uuid.New().String()

	return nil
}

func (v *User) Validate() error {

	if err := User_IDValidator.Validate(v.ID); err != nil {
		return err
	}

	if err := User_RoleValidator.Validate(v.Role); err != nil {
		return err
	}

	if err := User_EnvironmentValidator.Validate(v.Environment); err != nil {
		return err
	}

	if err := User_CreatedAtValidator.Validate(v.CreatedAt); err != nil {
		return err
	}

	if err := User_RequestIDValidator.Validate(v.RequestID); err != nil {
		return err
	}
	return nil
}
