// Code generated by elval-gen. DO NOT EDIT.
// Source: user.go

package main

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 5),
		Required:   make([]string, 0, 5),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "id")

		schema.Properties["id"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "role")

		prop.Enum = []any{"admin", "user", "guest"}

		schema.Properties["role"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["environment"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"
		prop.Format = "date-time"

		schema.Properties["createdat"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["requestid"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/examples/decorator.User"
}
