// Code generated by elval-gen. DO NOT EDIT.
// Source: string_checks.go

package string_checks

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Document) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 4),
		Required:   make([]string, 0, 4),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "url")

		schema.Properties["url"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "content")

		schema.Properties["content"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["imagename"] = prop
	}

	return schema
}

func (v *Document) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/string_checks.Document"
}

func (v *File) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "path")

		schema.Properties["path"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")

		schema.Properties["name"] = prop
	}

	return schema
}

func (v *File) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/string_checks.File"
}
