// Code generated by elval-gen. DO NOT EDIT.
// Source: string_checks.go

package string_checks

import (
	"context"
	errs "github.com/arkannsk/elval/pkg/errs"
	"github.com/arkannsk/elval/pkg/validator"
)

var (
	Document_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Contains("README"))
		return v
	}()

	Document_URLValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("URL")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.StartsWith("https://"))
		v.AddRule(validator.EndsWith(".com"))
		return v
	}()

	Document_ContentValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Content")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Contains("world"))
		return v
	}()

	Document_ImageNameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("ImageName")
		v.AddRule(validator.StartsWith("img_"))
		original := v
		v = validator.New[string]("ImageName")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()
)

func (v *Document) Decorate(ctx context.Context) error {

	return nil
}

func (v *Document) Validate() error {
	var err *errs.ValidationError

	if err = Document_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err = Document_URLValidator.Validate(v.URL); err != nil {
		return err
	}

	if err = Document_ContentValidator.Validate(v.Content); err != nil {
		return err
	}

	if err = Document_ImageNameValidator.Validate(v.ImageName); err != nil {
		return err
	}
	return nil
}

var (
	File_PathValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Path")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.EndsWith(".go"))
		return v
	}()

	File_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Contains("test"))
		return v
	}()
)

func (v *File) Decorate(ctx context.Context) error {

	return nil
}

func (v *File) Validate() error {
	var err *errs.ValidationError

	if err = File_PathValidator.Validate(v.Path); err != nil {
		return err
	}

	if err = File_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	return nil
}
