// Code generated by elval-gen. DO NOT EDIT.
// Source: upload.go

package file_upload

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *UploadRequest) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 5),
		Required:   make([]string, 0, 5),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "User avatar"

		schema.Properties["avatar"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Raw data stream"

		schema.Properties["payload"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "byte"

		prop.Description = "Base64 encoded"

		schema.Properties["data"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Custom avatar reader"

		schema.Properties["custom"] = prop
	}
	{
		prop := &oa.Schema{}
		prop.Type = "string"
		prop.Format = "binary"

		prop.Description = "Custom avatar reader"

		schema.Properties["stream"] = prop
	}

	return schema
}

func (v *UploadRequest) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/file_upload.UploadRequest"
}
