// Code generated by elval-gen. DO NOT EDIT.
// Source: person.go

package person

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *Person) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 7),
		Required:   make([]string, 0, 7),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](2)
		prop.MaxLength = oa.Ptr[int64](100)

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		schema.Required = append(schema.Required, "age")
		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Pattern = `^\+?[0-9]{8,15}$`
		prop.Format = "phone"

		schema.Properties["phone"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"
		prop.Format = "date-time"

		schema.Required = append(schema.Required, "birthdate")

		schema.Properties["birthdate"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		schema.Required = append(schema.Required, "tags")
		prop.Minimum = oa.Ptr[float64](1)
		prop.Maximum = oa.Ptr[float64](10)

		schema.Properties["tags"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "integer"

		schema.Properties["scores"] = prop
	}

	return schema
}

func (v *Person) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/person.Person"
}
