// Code generated by elval-gen. DO NOT EDIT.
// Source: person.go

package person

import (
	"github.com/arkannsk/elval/pkg/validator"
	"time"
)

var (
	Person_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(2))
		v.AddRule(validator.MaxLen(100))
		return v
	}()

	Person_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	Person_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Required[int]())
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		return v
	}()

	Person_PhoneValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Phone")
		v.AddRule(validator.Phone())
		original := v
		v = validator.New[string]("Phone")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	Person_BirthDateValidator = func() *validator.FieldValidator[time.Time] {
		v := validator.New[time.Time]("BirthDate")
		v.AddRule(validator.Required[time.Time]())
		v.AddRule(validator.After("2006-01-02", "1900-01-01"))
		v.AddRule(validator.Before("2006-01-02", "2024-12-31"))
		return v
	}()
)

// Validate проверяет структуру Person
func (v *Person) Validate() error {

	if err := Person_NameValidator.Validate(v.Name); err != nil {
		return err
	}

	if err := Person_EmailValidator.Validate(v.Email); err != nil {
		return err
	}

	if err := Person_AgeValidator.Validate(v.Age); err != nil {
		return err
	}

	if err := Person_PhoneValidator.Validate(v.Phone); err != nil {
		return err
	}

	if err := Person_BirthDateValidator.Validate(v.BirthDate); err != nil {
		return err
	}

	sliceValidator := validator.NewSliceValidator[string]("Tags")
	sliceValidator.Required()
	sliceValidator.Min(1)
	sliceValidator.Max(10)
	if err := sliceValidator.Validate(v.Tags); err != nil {
		return err
	}

	if len(v.Scores) > 0 {
		sliceValidator := validator.NewSliceValidator[int]("Scores")
		sliceValidator.NotZero()
		if err := sliceValidator.Validate(v.Scores); err != nil {
			return err
		}
	} else if true {
		return &validator.ValidationError{
			Field:   "Scores",
			Rule:    "not-zero",
			Message: "поле Scores не может быть пустым",
		}
	}

	return nil
}
