// Code generated by elval-gen. DO NOT EDIT.
// Source: person.go

package person

import (
	"fmt"
	"github.com/arkannsk/elval/pkg/validator"
	"time"
)

// Validate проверяет структуру Person
func (v *Person) Validate() error {
	var errs []error
	// Валидация поля Name

	{

		builder := validator.New[string]("Name")
		builder.AddRule(validator.Required[string]())
		builder.AddRule(validator.MinLen(2))
		builder.AddRule(validator.MaxLen(100))
		if err := builder.Validate(v.Name); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Email

	{

		builder := validator.New[string]("Email")
		builder.AddRule(validator.Required[string]())
		builder.AddRule(validator.Email())
		if err := builder.Validate(v.Email); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Age

	{

		builder := validator.New[int]("Age")
		builder.AddRule(validator.Required[int]())
		builder.AddRule(validator.Min[int](18))
		builder.AddRule(validator.Max[int](120))
		if err := builder.Validate(v.Age); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Phone

	{

		builder := validator.New[string]("Phone")
		builder.AddRule(validator.Phone())
		if v.Phone != "" {
			if err := builder.Validate(v.Phone); err != nil {
				errs = append(errs, err)
			}
		}
	}

	// Валидация поля BirthDate

	{

		builder := validator.New[time.Time]("BirthDate")
		builder.AddRule(validator.Required[time.Time]())
		builder.AddRule(validator.After("2006-01-02", "1900-01-01"))
		builder.AddRule(validator.Before("2006-01-02", "2024-12-31"))
		if err := builder.Validate(v.BirthDate); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Tags

	{
		builder := validator.NewSliceValidator[string]("Tags")
		builder.Required()
		builder.Min(1)
		builder.Max(10)
		if err := builder.Validate(v.Tags); err != nil {
			errs = append(errs, err)
		}
	}

	// Валидация поля Scores

	{
		builder := validator.NewSliceValidator[int]("Scores")
		builder.NotZero()
		if err := builder.Validate(v.Scores); err != nil {
			errs = append(errs, err)
		}
	}

	if len(errs) > 0 {
		return fmt.Errorf("ошибки валидации: %v", errs)
	}
	return nil

}
