// Code generated by elval-gen. DO NOT EDIT.
// Source: main.go

package main

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *APIResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}

		prop.OneOf = []*oa.Schema{
			{Ref: "#/components/schemas/github.com/arkannsk/elval/test/integration/oa_unique_refs/user.User"},
			{Ref: "#/components/schemas/github.com/arkannsk/elval/test/integration/oa_unique_refs/order.Order"},
		}

		schema.Properties["data"] = prop
	}

	return schema
}

func (v *APIResponse) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_unique_refs.APIResponse"
}

func (v *UserResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/user.User"

		schema.Properties["user"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Example = "success"

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *UserResponse) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_unique_refs.UserResponse"
}

func (v *OrderResponse) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 2),
		Required:   make([]string, 0, 2),
		Ref:        v.GlobalRef(),
	}

	{
		prop := &oa.Schema{}
		prop.Ref = "#/components/schemas/order.Order"

		schema.Properties["order"] = prop
	}

	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Example = "shipped"

		schema.Properties["status"] = prop
	}

	return schema
}

func (v *OrderResponse) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/oa_unique_refs.OrderResponse"
}
