// Code generated by elval-gen. DO NOT EDIT.
// Source: multiline_description.go

package multiline_description

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *User) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Description = "The full name of the user.\nIt should include first and last name.\nMax length is 50 characters."
		prop.Title = "User Name"

		schema.Properties["name"] = prop
	}

	return schema
}

func (v *User) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/multiline_description.User"
}

func (v *IgnoreField) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 1),
		Required:   make([]string, 0, 1),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Properties["name"] = prop
	}

	return schema
}

func (v *IgnoreField) GlobalRef() string {
	return "github.com/arkannsk/elval/test/integration/multiline_description.IgnoreField"
}
