// Code generated by elval-gen. DO NOT EDIT.
// Source: valid.go

package valid

import (
	oa "github.com/arkannsk/elval/pkg/openapi"
)

func (v *ValidUser) OaSchema() *oa.Schema {
	schema := &oa.Schema{
		Type:       "object",
		Properties: make(map[string]*oa.Schema, 6),
		Required:   make([]string, 0, 6),
		Ref:        v.GlobalRef(),
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "name")
		prop.MinLength = oa.Ptr[int64](3)
		prop.MaxLength = oa.Ptr[int64](50)

		schema.Properties["name"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		schema.Required = append(schema.Required, "email")
		prop.Pattern = `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`

		schema.Properties["email"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "integer"

		prop.Minimum = oa.Ptr[float64](18)
		prop.Maximum = oa.Ptr[float64](120)

		schema.Properties["age"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "string"

		prop.Enum = []any{"admin", "user", "guest"}

		schema.Properties["role"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "array"
		prop.Items = &oa.Schema{}

		prop.Items.Type = "string"

		schema.Properties["tags"] = prop
	}
	{
		prop := &oa.Schema{}

		prop.Type = "number"

		prop.Minimum = oa.Ptr[float64](0.01)
		prop.Maximum = oa.Ptr[float64](999.99)

		schema.Properties["price"] = prop
	}

	return schema
}

func (v *ValidUser) GlobalRef() string {
	return "github.com/arkannsk/elval/test/lint/valid.ValidUser"
}
