// Code generated by elval-gen. DO NOT EDIT.
// Source: valid.go

package valid

import (
	errs "github.com/arkannsk/elval/pkg/errs"
	validator "github.com/arkannsk/elval/pkg/validator"
)

var (
	ValidUser_NameValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Name")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.MinLen(3))
		v.AddRule(validator.MaxLen(50))
		return v
	}()

	ValidUser_EmailValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Email")
		v.AddRule(validator.Required[string]())
		v.AddRule(validator.Email())
		return v
	}()

	ValidUser_AgeValidator = func() *validator.FieldValidator[int] {
		v := validator.New[int]("Age")
		v.AddRule(validator.Min[int](18))
		v.AddRule(validator.Max[int](120))
		return v
	}()

	ValidUser_RoleValidator = func() *validator.FieldValidator[string] {
		v := validator.New[string]("Role")
		v.AddRule(validator.Enum[string]("admin", "user", "guest"))
		original := v
		v = validator.New[string]("Role")
		v.AddRule(validator.SkipIfZero(original.Validate))
		return v
	}()

	ValidUser_TagsValidator = func() *validator.SliceValidator[string] {
		v := validator.NewSliceValidator[string]("Tags")
		v.NotZero()
		return v
	}()
	ValidUser_PriceValidator = func() *validator.FieldValidator[float64] {
		v := validator.New[float64]("Price")
		v.AddRule(validator.Min[float64](0.01))
		v.AddRule(validator.Max[float64](999.99))
		return v
	}()
)

func (v *ValidUser) Validate() error {
	var err *errs.ValidationError
	if v.Name == "" {
		return errs.NewValidationError("Name", "required", "field is required")
	}
	if err = ValidUser_NameValidator.Validate(v.Name); err != nil {
		return err
	}
	if v.Email == "" {
		return errs.NewValidationError("Email", "required", "field is required")
	}
	if err = ValidUser_EmailValidator.Validate(v.Email); err != nil {
		return err
	}
	if err = ValidUser_AgeValidator.Validate(v.Age); err != nil {
		return err
	}
	if err = ValidUser_RoleValidator.Validate(v.Role); err != nil {
		return err
	}
	if err = ValidUser_TagsValidator.Validate(v.Tags); err != nil {
		return err
	}
	if err = ValidUser_PriceValidator.Validate(v.Price); err != nil {
		return err
	}
	return err
}
